$ 
$ +SNOTICE
$ 
$  $TOG: DtMail.msg /main/4 1998/05/22 17:08:11 rafi $
$ 
$  RESTRICTED CONFIDENTIAL INFORMATION:
$ 
$  The information in this document is subject to special
$  restrictions in a confidential disclosure agreement between
$  HP, IBM, Sun, USL, SCO and Univel.  Do not distribute this
$  document outside HP, IBM, Sun, USL, SCO, or Univel without
$  Sun's specific written approval.  This document and all copies
$  and derivative works thereof must be returned or destroyed at
$  Sun's request.
$ 
$  Copyright 1993, 1994, 1995 Sun Microsystems, Inc.  All rights reserved.
$ 
$ +ENOTICE
$ 

$quote "

$ 
$ Strings from dtmail/RoamApp.C

$set 1
1 "確定"
$ 	    /* NL_COMMENT
$ 	     * This is a menu label, please refer to the resource file "Dtmail" for
$            * appropriate mnemonics tranlation
$ 	     */
2 "郵件選項..."
3 "自動回信"
4 "特性更新中..."


$ 
$ Strings from dtmail/RoamMenuWindow.C

5 "取消"
6 "電子郵件"
7 "電子郵件"
8 "電子郵件"
9 "刪除"
10 "下一個"
11 "前一個"
12 "回覆寄件人"
13 "列印"
14 "送件人"
15 "主題"
16 "日期和時間"
17 "大小"
$ 	    /* NL_COMMENT
$            * Menu labels in Main Mailer (from RoamMenuWindow.C).
$            * The following menu labels require translation plus parenthesized 
$            * mnemonics for all Asian locales. Please refer to the resource file 
$            * "Dtmail" for each mnemonics.
$ 	     * Message 18-22,25,28,29 are menu labels for "Mailbox" pull down menu.
$            * Message 30,31,33-40 are menu labels for "Message" pull down menu. 
$            * Message 43-45 are menu labels for "Edit" pull down menu. 
$            * Message 47--55 are menu labels for "View" pull down menu. 
$            * Message 56-63 are menu labels for "Compose" pull down menu. 
$            * Message 64,65,221 are menu labels for "Move" pull down menu. 
$            * Message 66,68,69 are menu labels for "Attachment" pull down menu. 
$            * Message 71-77 are menu labels for "Help" pull down menu. 
$ 	     */
18 "郵箱"
19 "檢查是否有新郵件"
20 "開啟收件箱"
21 "開啟收件箱"
22 "新郵件..."
23 "電子郵件 - 新郵件"
24 "新郵件"
25 "開啟..."
26 "電子郵件 - 開啟"
27 "開啟"
28 "銷毀已刪除的訊息"
29 "關閉"
30 "開啟"
31 "儲存為文字檔..."
32 "電子郵件 - 訊息 - 儲存為文字檔"
33 "複製到"
34 "列印..."
35 "尋找..."
36 "全部選取"
37 "刪除"
38 "取消刪除前一個訊息"
39 "從列表中取消刪除..."
40 "訊息"
41 "移動"
42 "電子郵件 - 訊息"
43 "複製"
44 "全部選取"
45 "編輯"
46 "電子郵件 - 文字"
47 "下一個"
48 "前一個"
49 "表頭縮寫"
50 "依日期/時間排序"
51 "依送件人排序"
52 "依主題排序"
53 "依大小排序"
54 "依狀態排序"
55 "察看"
56 "新訊息"
57 "新訊息，含括全部"
58 "轉送訊息"
59 "回覆送件人"
60 "回覆所有人"
61 "回覆送件人，含括"
62 "回覆所有人，含括"
63 "回信"
64 "移動"
65 "其他郵箱..."
66 "另存新檔..."
67 "電子郵件 - 附屬裝置 - 另存新檔"
68 "全部選取"
69 "附屬裝置"
70 "電子郵件 - 附屬裝置"
71 "概觀"
72 "工作"
73 "參照"
74 "關於項目"
75 "使用輔助說明"
76 "輔助說明"
77 "關於電子郵件..."
78 "電子郵件不清楚此郵箱的狀態。\n請選擇「確定」關閉郵箱後，再重新啟動電子郵件。"
79 "轉換中... 完成 %d %%"
80 "電子郵件"

$ 
$ Strings from dtmail/AttachArea.C

81 "電子郵件"
82 "電子郵件"
83 "電子郵件"


$ 
$ Strings from dtmail/Attachment.C

84 "%s 是一個可執行的附屬裝置。  您想執行嗎?"
85 "電子郵件"
86 "電子郵件"
87 "電子郵件"
88 "電子郵件"


$ 
$ Strings from dtmail/RoamCmds.C

89 "電子郵件 - 其他郵箱"
90 "移動"
91 "列印..."
92 "確定"
93 "儲存"
94 "儲存"
95 "儲存"
96 "清空"
97 "改名"
98 "電子郵件 - 改名"
99 "電子郵件"
100 "確定"
101 "取消"
102 "您已在自動回信以外的選項中\n使用了轉送機能。  自動回信執行時 \n，自動回信會附加到該選項\n的轉送作業中。  您確定要啟動自動回信嗎?\0"
103 "電子郵件"
104 "您在 .forward 檔案中已執行自動回信程式。\n請從說明文件中查出如何停止此程式，並將它從 .forward 檔案中刪除。\n問題解決後，請再試一次此指令。\0"
105 "無法開啟 .vacation.msg 檔案 -- 沒有寫入許可權。"
106 ".vacation.msg 檔案已存在。  要以新文字取代嗎?"
107 "無法開啟 .vacation.msg 檔案 -- 沒有寫入許可權。"
108 "我正在休假當中"
$ 	    /* NL_COMMENT
$ 	     * This is the default value of the subject field in the
$ 	     * message that gets returned to the sender when vacation
$ 	     * is turned on.
$ 	     */
109 "我正在休假當中。\n等我回來後，會閱讀您送來有關 \"$SUBJECT\" 的郵件。\n"


$ 
$ Strings from dtmail/MsgScrollingList.C

110 "N"
$ /* NL_COMMENT
$  * In a mailer container window's message scrolling list, a "N" appears
$  * to the left of a mail message header indicating that the mail message
$  * is "new" (just arrived and not yet viewed by the user).
$  * There is only space to display 1 character.  If "N" needs to be translated,
$  * please make sure the translation is only 1 character.
$  */
111 "N"
$ /* NL_COMMENT
$  * In a mailer container window's message scrolling list, a "N" appears
$  * to the left of a mail message header indicating that the mail message
$  * is "new" (just arrived and not yet viewed by the user).
$  * There is only space to display 1 character.  If "N" needs to be translated,
$  * please make sure the translation is only 1 character.
$  */
112 "N"
$ /* NL_COMMENT
$  * In a mailer container window's message scrolling list, a "N" appears
$  * to the left of a mail message header indicating that the mail message
$  * is "new" (just arrived and not yet viewed by the user).
$  * There is only space to display 1 character.  If "N" needs to be translated,
$  * please make sure the translation is only 1 character.
$  */
113 "N"
$ /* NL_COMMENT
$  * In a mailer container window's message scrolling list, a "N" appears
$  * to the left of a mail message header indicating that the mail message
$  * is "new" (just arrived and not yet viewed by the user).
$  * There is only space to display 1 character.  If "N" needs to be translated,
$  * please make sure the translation is only 1 character.
$  */
114 "N"


$ 
$ Strings from dtmail/Undelete.C

115 "取消刪除"
116 "關閉"

$ 
$ Strings from dtmail/SendMsgDialog.C

$ 	    /* NL_COMMENT
$            * Menu labels in Compose dialog (from SendMsgDialog.C).
$            * The following menu labels require translation plus parenthesized 
$            * mnemonics for all Asian locales. Please refer to the resource file 
$            * "Dtmail" for each mnemonics.
$ 	     * Message 117,121,122,125,127-129 are menu labels for "File" pull down menu.
$            * Message 130-134,139,140,155,156 are menu labels for "Edit" pull down menu. 
$            * Message 141,142,145,147-150,226 are menu labels for "Attachment" pull down menu. 
$            * Message 152-154,157 are menu labels for "Format" pull down menu. 
$            * Message 56-63 are menu labels for "Compose" pull down menu. 
$            * Message 64,65,221 are menu labels for "Move" pull down menu. 
$            * Message 66,68,69 are menu labels for "Attachment" pull down menu. 
$            * Message 71-77 are menu labels for "Help" pull down menu. 
$ 	     */
117 "送出"
118 "關閉"
119 "新訊息"
120 "電子郵件"
121 "檔案"
122 "含括..."
123 "電子郵件 - 含括"
124 "含括"
125 "儲存為文字檔..."
126 "電子郵件 - 儲存為文字檔"
127 "日誌訊息"
128 "作為...送出"
129 "關閉"
130 "編輯"
131 "還原"
132 "剪取"
133 "複製"
134 "黏貼"
135 "特殊黏貼"
136 "加方括弧"
137 "縮排"
138 "清除"
139 "刪除"
140 "全部選取"
141 "附屬裝置"
142 "增加檔案..."
143 "電子郵件 - 增加"
144 "增加"
145 "另存新檔..."
146 "電子郵件 - 附屬裝置 - 另存新檔"
147 "刪除"
148 "取消刪除"
149 "改名"
150 "全部選取"
$       /* NL_COMMENT
$        * This is an obsolete message.  It is replaced by message 226
$        * in set 1.
$        */
151 "顯示窗格"
152 "格式"
153 "自動換行"
154 "設定值..."
155 "尋找/更改..."
156 "拼字檢查..."
157 "模板"
158 "電子郵件 - 附屬裝置"
159 "電子郵件 - 回信"
160 "新訊息"
$       /* NL_COMMENT
$        * This is the label for a toggle item in a menu.  When the item
$        * is set to "Show List", the Attachment List is mapped in the
$        * Compose Window.  This message replaces message 151 in set 1.
$        */


$ 
$ Strings from dtmail/ViewMsgDialog.C

161 "複製"
162 "全部選取"
163 "編輯"
164 "另存新檔..."
165 "電子郵件 - 附屬裝置 - 另存新檔"
166 "全部選取"
167 "附屬裝置"
168 "電子郵件 - 附屬裝置"
169 "電子郵件 - 文字"
170 "概觀"
171 "工作"
172 "參照"
173 "關於項目"
174 "使用輔助說明"
175 "輔助說明"
176 "關於電子郵件..."
177 "電子郵件"


$ 
$ Strings from dtmail/DtMailGenDialog.C

$  /* NL_COMMENT
$   * 178 and 179 are obsolete messages, replaced by messages
178 "電子郵件 - 關於 Dtmail"
179 "Dtmail Version 1.0"
180 "確定"
181 "確定"
182 "取消"

$ 
$ Strings from dtmail/FindDialog.C

183 "尋找"
$  /* NL_COMMENT
$   * This is an obsolete message.  Replaced by message 220 in set 1
$   */
184 "尋找並選取全部"
185 "清除"
186 "關閉"
187 "輔助說明"
188 "收件人："
189 "寄件人："
190 "主題："
191 "副本："
192 "電子郵件 - 尋找"
193 "往下尋找"
194 "往回尋找"
$  /* NL_COMMENT
$   * This message replaces message 184 in set 1
$   */


$ 
$ Strings from dtmail/Editor.C

195 "------------- Begin Forwarded Message -------------\n\n" 
196 "------------- Begin Included Message -------------\n\n" 
197 "------------- End Forwarded Message -------------\n\n" 
198 "------------- End Included Message -------------\n\n" 

$ 
$ Strings from dtmail/XmTextEditor.C

199 "\n------------- Begin Included Message -------------\n" 
200 "\n------------- End Included Message -------------\n" 

$ 
$ Strings from dtmail/DtEditor.C

201 "\n------------- Begin Included Message -------------\n" 
202 "\n------------- End Included Message -------------\n" 

$ 
$ Strings from dtmail/Editor.C
$ 195 "------------- 轉送訊息開始 -------------\n\n"
$ 196 "------------- 含括訊息開始 -------------\n\n"
$ 197 "------------- 轉送訊息結束 -------------\n\n"
$ 198 "------------- 含括訊息結束 -------------\n\n"
$ 
$ Strings from dtmail/XmTextEditor.C
$ 199 "\n------------- 含括訊息開始 -------------\n"
$ 200 "\n------------- 含括訊息結束 -------------\n"
$ 
$ Strings from dtmail/DtEditor.C
$ 201 "\n------------- 含括訊息開始 -------------\n"
$ 202 "\n------------- 含括訊息結束 -------------\n"

$ 
$ Strings from dtmail/ComposeCmds.C

203 "電子郵件"
204 "無法建立回信視窗。"
205 "電子郵件"
206 "無法建立回信視窗。"
207 "電子郵件"
208 "無法建立回信視窗。"
209 "電子郵件"
210 "無法建立回信視窗。"
211 "電子郵件"
212 "模板不存在。"
213 "電子郵件"
214 "模板似乎已損毀。"
215 "電子郵件"
216 "記憶體不足，無法載入模板。"
217 "電子郵件"
218 "模板似乎已損毀。"

$ 
$ Strings from dtmail/SortCmd.C

219 "排序中..."

220 "全部選取"
221 "收件箱"

222 "%a %b %d %k：%M"
$ /* NL_COMMENT
$  * The "%a %b %d %k:%M" is the time and date format, please refer to 
$  * strftime man page for explanation of each format.
$  */
223 "%a %b %d %H：%M"
$ /* NL_COMMENT
$  * The "%a %b %d %H:%M" is the time and date format, please refer to 
$  * strftime man page for explanation of each format.
$  */
224 "%a %b %d %k：%M"
$ /* NL_COMMENT
$  * The "%a %b %d %k:%M" is the time and date format, please refer to 
$  * strftime man page for explanation of each format.
$  */
225 "%a %b %d %H：%M"
$ /* NL_COMMENT
$  * The "%a %b %d %H:%M" is the time and date format, please refer to 
$  * strftime man page for explanation of each format.
$  */
226 "顯示列表"

$ String from Undelete.C, Deleted Messages window title
227 "電子郵件 - Deleted Messages"

$ Strings from SendMsgDialog.C, Add Bcc, Delete Bcc menu buttons
228 "增加"
229 "刪除"
230 "傳送"

$  /* NL_COMMENT
$   * This string is displayed on the find dialog status line
$   * when searching for a matching message.
$   */
231 "搜尋..."

$        /* NL_COMMENT
$         * These strings are displayed on the find dialog status line
$         * when one or more matching messages are found.  The first
$         * string is displayed when there is one matching message,
$         * and the second string is displayed when there is more than
$         * one.  The %d is the number of messages that matched.
$         */
232 "選定 1 訊息"
233 "選定 %d 訊息"

$  /* NL_COMMENT
$   * This string is displayed on the find dialog status line when
$   * no matching messages were found.
$   */
234 "找不到相符訊息"

$  /* NL_COMMENT
$   * These strings replace strings 178 and 179.  They are used in
$   * the "About Mailer" dialog box.
$   */
235 "電子郵件 - 關於電子郵件"
236 "電子郵件 1.0 版本"

$set 2
1 "電子郵件"
2 "ToolTalk 尚未進行起始設定。  電子郵件無法在沒有 ToolTalk 的情況下執行。\n請嘗試啟動 /usr/dt/bin/dtsession，或聯絡您的系統管理員。"

3 "視窗無法進行起始設定。  結束中。\n"
4 "電子郵件安裝有問題，\n\因執行群組設定錯誤，\n\所以無法執行"
5 "您不具許可權，無法察看 %s"
$ 	    /* NL_COMMENT
$ 	     * The %s is the name of the mailbox the user doesn't have
$ 	     * permission to view.
$ 	     */
6 "郵箱 %s 是一個目錄，無法開啟。"
7 "無法將 %s 清空。  因為它不存在。"
8 "儲存區 %s 已清空。"
9 "錯誤 - 無法清空 %s"
10 "電子郵件"
11 "%s"
12 "電子郵件"
13 "電子郵件"
14 "附屬裝置必須先選取，才能執行「另存新檔\」指令將它存到一個\n\檔案內。"

15 "錯誤 - 無法取得 mailrc。"
16 "尚未選取訊息。"
$ 	/* NL_COMMENT
$ 	 * No mail message has been selected by the user.
$ 	 */


17 "您已編輯過 \"%s\"，仍舊要刪除嗎?"
18 "錯誤：無法含括檔案 %s"
19 "附屬裝置必須先選取，才能執行「另存新檔」指令將它存到一個\n\檔案內。"


20 "附屬裝置必須先選取，才能執行「另存新檔」指令將它存到一個\n\檔案內。"

21 "電子郵件"



$set 3
1 "自動儲存中..."

2 "起始設定中..."
3 "郵箱 %s 不存在。\n\您想建立這個名稱的郵箱嗎?"
4 "電子郵件"
5 "確定"
6 "郵箱 %s 被鎖定。\n\您可以用手動的方式解除鎖定，然後再試一次；\n\或是聯絡您的系統管理員。"
7 "電子郵件"
8 "確定"
9 "確定"
10 "確定"
11 "確定"
12 "%s"
13 "訊息 %d (共有 %d 則訊息)，%d 則新訊息，%d 則已刪除"
14 "訊息 %d (共有 %d 則訊息)，%d 則新訊息，%d 則已刪除"
$ 	/* NL_COMMENT
$ 	 * The user will see the following message display as:
$ 	 * "Message 3 of 10, 2 new, 6 deleted"
$ 	 * This means ??? -- Explain to translator.
$ 	 */
15 "儲存中..."
16 "電子郵件"
$ 		/* NL_COMMENT
$ 		 * This dialog comes up when the user tries to quit the
$ 		 * mailbox and the user is asked if he wants to destroy
$ 		 * the messages marked for deletion.
$ 		 */
$		/* NL_COMMENT
$		 * Messages 16 and 17 are no longer being used.  They are
$		 * being replaced by messages 86 and 87.
$		 */
17 "要從這個郵箱中銷毀您標示要刪除\n\的訊息嗎?"
18 "確定"
19 "取消"
20 "開啟郵箱中..."
21 "%s 已存在。\n\要重寫嗎?"
22 "電子郵件"
23 "無法重寫 %s。\n請檢查檔案的許可權，然後重試一次。"
24 "電子郵件"
25 "儲存區載入中..."
26 "檔案夾摘要資訊"
27 "載入中..."
28 "清空儲存區"
29 "確定"
30 "確定"
31 "確定"
32 "正在銷毀已刪除的訊息..."
33 "確定"

34 "%s 不存在。"
35 "無法開啟 %s。"
36 "無法配置記憶體。"
37 "附屬裝置摘要"
38 "附屬裝置"
39 "附屬裝置"
$ 	/* NL_COMMENT
$ 	 * "attachments" is the plural form of "attachment".
$ 	 */
40 "附屬裝置"
41 "已刪除"

42 "%s 已存在。  要取代嗎?"
43 "無法取代 %s。"
44 "無法建立 %s。"
45 "無法建立 %s。"


46 "清空儲存區"
47 "%s 已存在。\n要重寫嗎?"
48 "電子郵件"
49 "無法重寫 %s。\n\請檢查檔案許可權之後重試。"
50 "電子郵件"
51 "無法建立 %s。"
52 "電子郵件"
53 "無法寫入 %s。"
54 "電子郵件"
55 "無法建立 %s。"
56 "電子郵件"
57 "將附屬裝置改名為"
58 "回信視窗含有一些在視窗\n\關閉時會遺失的文字或附屬裝置，\n\您確定要關閉回信視窗嗎?"
59 "沒有記憶體"
60 "記憶體不足，無法載入現存的 .vacation.msg 檔案。"
61 "電子郵件"
62 "現存的 .vacation.msg 檔案似乎已損毀。"


63 "選取一個訊息來移動。"
64 "選取一個訊息來複製。"
65 "%d 個訊息移到 %s"
66 "%d 個訊息移到 %s"
67 "%d 個訊息複製到 %s"
68 "%d 個訊息複製到 %s"
69 "視區已存在。  請將它提至前端。"
$ 	/* NL_COMMENT
$ 	* The current mail message selected is already displayed in a separate
$ 	* window.  Therefore this 'separate' window will be raised in front
$ 	* of existing windows so the user can see it.
$ 	*/



70 "撰寫無法投遞的郵件..."
71 "電子郵件"
72 "確定"
73 "取消"
74 "確定"

75 "確定"
76 "確定"

77 "您有一個已開啟的附屬裝置，可能含有尚未儲存修改的內容。\n傳送這個訊息將會破壞與這個已開啟的附屬裝置\n的連接。  任何尚未儲存修改的內容將不會成為這個訊息的\n一部份。  您可以使用「另存新檔」以儲存修改的內容，在連接被\n破壞以後，不過修改的內容將不會成為這個附屬裝置\n的一部份。"
78 "設定郵件選項..."
79 "銷毀並退出"
80 "不要銷毀，退出"
81 "這個附屬裝置可能含有可以造成嚴重損害的\n\命令。  建議您最好先確定以後，再執行這個附屬裝置。  如果您確定，請按「確定」； 請按「取消」，以取消執行。"
82 "有別人正在使用這個信箱。\n您想要要求鎖定單獨操作嗎？"
83 "電子郵件無法獲取鎖定單獨操作這個信箱。\n您想要以唯讀的狀態開啟這個信箱嗎？"

$            /* NL_COMMENT
$             * The following sentence means %d number of mail messages have
$             * been deleted from the mail folder.  This is the plural form
$             * of the message that gets printed if more than one message
$             * is moved.
$             */
84 "刪除 %d 訊息"

$            /* NL_COMMENT
$             * The following sentence means %d number of mail messages have
$             * been deleted from the mail folder.  This is the singular
$             * form of the message that gets printed if only one message
$             * is moved.
$             */
85 "刪除 %d 訊息"
86 "檢查新的郵件..."
$		/* NL_COMMENT
$		 * This dialog comes up when the user tries to quit the
$		 * mailbox.  The user is asked if they want to destroy
$		 * the deleted messages.
$		 */
87 "電子郵件 - 關閉"
88 "銷毀刪除的訊息並關閉這個信箱嗎？"
89 "銷毀並關閉"
90 "保留並關閉"
$        /* NL_COMMENT
$         * Post a dialog explaining that the action was invalid
$         */
91 "無法執行無效的動作。"
$        /* NL_COMMENT
$         * Post a dialog explaining that the action failed.
$         */
92 "執行動作失敗！"
93 "選定的圖像 %s 真正能夠執行。\n按一下「確定」以執行，或「取消」以結束。"
94 "電子郵件無法單獨鎖定這個\n信箱，因為系統未回應。\n\n只有在此時，您可以選擇去開啟這個信箱\n為唯讀狀態，或開啟這個信箱為讀寫狀態而不單獨\n鎖定，(只有在無人使用這個信箱時，才如此使用)。"
95 "唯讀"
96 "讀寫"


$set 5
1 "電子郵件"
2 "電子郵件"
3 "若原樣送出此訊息\n\	    則附屬裝置中所作的修改將\n\	    會遺失。"
$    /* NL_COMMENT
$     * The user tried to send a messages without saving changes in
$     * some open attachments.  This warning makes sure that is what
$     * the user intended.
$     */
4 "請只選取一個附屬裝置\n\	    然後選取「改名」"
$       /* NL_COMMENT
$        * Mailer ran out of memory.  Ask the user to quit some other
$        * applications so there will be more memory available.
$        */
5 "訊息中某些位址有誤，\n因為它並未參照到系統中任何已知的使用者。\n請確定是否所有的位址均有效，然後再試一次。"
$       /* NL_COMMENT
$        * Mailer ran out of memory.  Ask the user to quit some other
$        * applications so there will be more memory available.
$        */
6 "電子郵件 的記憶體不足，無法送出\n這個訊息。\n請結束其他應用程式，\n然後再傳一次。"
$       /* NL_COMMENT
$        * There was an error from the mail transport (sendmail).
$        */
7 "在傳送您的訊息時有錯誤發生。\n請檢查這個訊息是否被收到。  如果尚未收到，\n或許您需要重傳一次。"
$       /* NL_COMMENT
$        * User trying to send a message that has no addressed recipient.
$        */
8 "請嘗試「傳送」在指定這個訊息的接收者之後，\n\在 收件人:, 副本:, 或 Bcc: 欄位。"

$set 12
1 "附屬裝置"
2 "附屬裝置"
3 "displayCount"
4 "無法連接 FIFO 檔案：%s"
5 "無法連接字元特殊檔案：%s"
6 "無法連接目錄：%s"
7 "無法連接區段特殊檔案：%s"
8 "無法連接 socket 檔案：%s"


$set 13
1 "無法建立"
2 "無法寫入"

$ 
$ Strings from dtmail/AttachCmds.C

$set 14
1 "加入附屬裝置"
2 "無法開啟 %s"
3 "無法連接 FIFO 檔案：%s"
4 "無法連接字元特殊檔案：%s"
5 "無法連接目錄：%s"
6 "無法連接區段特殊檔案：%s"
7 "無法連接 socket 檔案：%s"
8 "無法開啟 %s"
9 "電子郵件 - 附屬裝置改名"
10 "說明"
11 "將附屬裝置儲存為"

$set 15
1 "您已經有尚未儲存的修改內容。\n您可以儲存您的修改內容，或放棄您的修改內容，\n或返回您上次對話的位置。"
2 "儲存"
3 "放棄"
