$ $XConsortium: dtscreen.msg /main/3 1995/12/08 09:50:38 rswiston $
$ @(#)25	1.1.1.1  com/XTOP/aixclients/xlock/xlock.msg, xclients, r5gos325, 9333325d 5/6/93 20:13:37
$ 
$ COMPONENT_NAME: dtscreen
$ 
$ FUNCTIONS: dtscreen.msg
$ 
$ 
$ (C) COPYRIGHT International Business Machines Corp. 1987, 1993
$ All Rights Reserved
$ Licensed Materials - Property of IBM
$ 
$ US Government Users Restricted Rights - Use, duplication or
$ disclosure restricted by GSA ADP Schedule Contract with IBM Corp.
$ 
$ 

$quote "

$set 2
$ message file created 1993

1 "1386-101 %s：命令行選項錯誤 \"%s\"\n\n"
2 "1386-102 \n鍵入 %s -help 即可得到完整的說明。\n\n"

3 "1386-103 用法：\n        %s [-options ...]\n\n\
	 選項包括：\n"
5 "1386-105    %-28s %s\n\t 模態為以下之一：\n\", \"-mode mode\", \"animation mode"

7 "1386-107 未知的模態："
10 "1386-110 無法配置：%s\n"
11 "1386-111 配置 %d 個圖像單元\n"

17 "1386-117 %s：無法開啟顯示器 %s。\n"
18 "1386-118 %s：GetResource - 無法配置記憶體"
19 "1386-119 %s：-display 引數格式錯誤，\"%s\"\n"

20 "1386-120 -batchcount 引數須為正數。"
21 "1386-121 -saturation 引數必須介於 0.0 與 1.0 之間。"

25 "1386-125 %s：只能支援 %d 個螢幕。\n"
30 "1386-130 -delay 引數須為正數。"
35 "1386-135 無法配置：%s，以 %s 取代\n"
40 "%s：無法找到視窗來繪圖。使用 -create\n\
        選項可讓 %s 建立它自己的視窗。\n"

