$ $XConsortium: dttypes.msg /main/2 1996/07/24 19:03:29 drk $

$quote "


$set 1
1	"Dttype"
$ Do not Translate
2	"Dttype"
$ Do not Translate
3	"無法將任何物件起始設定\n"
4	"空字串"
$ this should mean a "Empty string".
5	"=============== %s ===============\n"
$ Do not Translate
6	"\0"
$ Do not Translate
7	"%s\n"
$ Do not Translate
8	""
$ Do not Translate
9	"自 %s載入\n"
10	"不明的"
11	"\t%s"
$ Do not Translate
12	"\0"
$ Do not Translate
13	" ：\t%s"
$ Do not Translate
14	"\0"
$ Do not Translate
15	"\n"
$ Do not Translate
16	"-db"
$ Do not Translate
17	"-w"
$ Do not Translate
18	"-l"
$ Do not Translate
19	"rec_info"
$ Do not Translate
20	"rec_name"
$ Do not Translate
21	"fld_name"
$ Do not Translate
22	"fld_value"
$ Do not Translate
23	"all"
$ Do not Translate
24	"錯誤 = %o, %s\n"
$ Translate "error" only
25	"用法:  dttypes [-help]\n\tdttypes [-type filename]\n\tdttypes [-db database] [-w [rec_name regexp] [fld_name regexp]\n\t\t\t[fld_value regexp]]\n\t\t[-l [rec_name] [rec_info] [fld_name regexp] [fld_value]]\n"
$ Translate only the following： "filename" "database" "regexp"
26	"-type"
$ Do not Translate
27	"%s 的類別是 %s\n"
28	"$"
$ Do not Translate
29	"--------------------- %s ----------------\n"
$ Do not Translate
30	"無效的資料庫\n"
31	"不是有效的引數\n"
32	"無效的 rec_info 欄位在  -w 選項中\n"
$ do not translate "rec_info" or "-w"
33	"不在 -w 或 -l 選項中\n"
$ do not translate "-w" or "-l"
34	"不明的選項\n"
35	"-help"
$ Do not Translate
36	"一般表示式 %s 中有錯誤\n"

