$ $XConsortium$

$ ========================================================================
$ = Message source text file for App Builder's libABobjXm utility library.
$ = @(#)libABobjXm.msg	1.2 13 Sep 1994 dtappbuilder/src/libABobjXm
$ ========================================================================

$quote "

$ The set number set below must be syncronized with the #define in objxmP.h
$set 203
1 "警告：%s ：無法將檔案名稱[%s]轉換成圖像映\n"
2 "警告：%s ：未指定檔案名稱\n"
3 "錯誤：%s：沒有物件附著物\n"
4 "具體化錯誤：%s：母程序之widget-ID 是空白的\n"
5 "具體化錯誤：%s：無法將功能表具體化\n"
6 "具體化錯誤：物件必須有有效的名稱\n"
7 "具體化錯誤：%s：物件必須有 widget 等級\n"
8 "內部錯誤：計數不符合\n"
9 "錯誤：objxm_comp_get_subobj - 物件未 xmconfigured：%s\n"
10 "檔案夾"
11 "過濾器"
12 "鍵入檔名"
13 "更新"
