$ $XConsortium$

$ ========================================================================
$ = Message source text file for App Builder's libAButil utility library.
$ = @(#)libAButil.msg	1.2 13 Sep 1994 dtappbuilder/src/libAButil
$ ========================================================================

$quote "

$ The set number set below must be syncronized with the #define in utilP.h
$set 202
1 "ISTR：配置到整數陣列時發生錯誤\n"
2 "ISTR：為字串配置空間時發生錯誤\n"
3 "ISTR：配置記憶體時發生錯誤"
4 "內部錯誤"
5 "遞迴式函式呼叫"
6 "不被許可"
7 "無法開啟"
