$ 
$ +SNOTICE
$ 
$  $XConsortium: MotifApp.msg /main/3 1995/11/08 14:04:03 rswiston $
$ 
$  RESTRICTED CONFIDENTIAL INFORMATION:
$ 
$  The information in this document is subject to special
$  restrictions in a confidential disclosure agreement between
$  HP, IBM, Sun, USL, SCO and Univel.  Do not distribute this
$  document outside HP, IBM, Sun, USL, SCO, or Univel without
$  Sun's specific written approval.  This document and all copies
$  and derivative works thereof must be returned or destroyed at
$  Sun's request.
$ 
$  Copyright 1993 Sun Microsystems, Inc.  All rights reserved.
$ 
$ +ENOTICE
$ 

$ -------------------------------------
$ MotifApp/Application.C
$ 

$quote "

$ -------------------------------------
$ MotifApp/AskFirstCmd.C
$ 

$quote "


$set 1
1 "您真的要執行這個命令嗎?"
$ -------------------------------------
$ MotifApp/DialogManager.C
$ 

$quote "


2 "確定"
3 "取消"
$ -------------------------------------
$ MotifApp/Help.C
$ 

$quote "


4 "DtMail 版本對話"
5 "DtMail 版本對話"
6 "您必須在應用程式中選取一個元件。\n"
7 "DtMail Help"
8 "DtMail Help"


$quote "


9 "Close this folder?"
$ -------------------------------------
$ MotifApp/WarnNoUndoCmd.C
$ 

$quote "


10 "此指令無法還原。仍舊要繼續嗎?"

$quote "

$set 2
1 "選擇錯誤，無法繼續\n" 
2 "使用者自行中斷選擇。\n" 
$ -------------------------------------
$ MotifApp/QuitCmd.C
$ 
