#!/bin/sh
# PROVIDE: dtlogin
# REQUIRE: DAEMON LOGIN wscons
# KEYWORD: shutdown

$_rc_subr_loaded . /etc/rc.subr

name="dtlogin"
rcvar=$name
command="/usr/dt/bin/${name}"
command_args="-daemon"
pidfile=/var/dt/Xpid
extra_commands=""

load_rc_config $name
run_rc_command "$1"
