/*
 * CDE - Common Desktop Environment
 *
 * Copyright (c) 1993-2012, The Open Group. All rights reserved.
 *
 * These libraries and programs are free software; you can
 * redistribute them and/or modify them under the terms of the GNU
 * Lesser General Public License as published by the Free Software
 * Foundation; either version 2 of the License, or (at your option)
 * any later version.
 *
 * These libraries and programs are distributed in the hope that
 * they will be useful, but WITHOUT ANY WARRANTY; without even the
 * implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR
 * PURPOSE. See the GNU Lesser General Public License for more
 * details.
 *
 * You should have received a copy of the GNU Lesser General Public
 * License along with these libraries and programs; if not, write
 * to the Free Software Foundation, Inc., 51 Franklin Street, Fifth
 * Floor, Boston, MA 02110-1301 USA
 */
/* $XConsortium: externC.h /main/3 1995/11/06 17:12:49 rswiston $ */
#ifdef	__cplusplus
extern "C" {
#endif
/*
 * File: argChooser_ui.h
 * Contains: Declarations of module objects, user create procedures,
 *           and callbacks.
 *
 * This file was generated by dtcodegen, from module argChooser
 *
 *    ** DO NOT MODIFY BY HAND - ALL MODIFICATIONS WILL BE LOST **
 */
#ifndef _ARGCHOOSER_UI_H_
#define _ARGCHOOSER_UI_H_

#include <stdlib.h>
#include <X11/Intrinsic.h>
#include "dtb_utils.h"

/*
 * User Interface Objects
 */
/*
 * Shared data structures
 */

typedef struct {
    Widget	IN_item;
    Widget	OUT_item;
    Widget	INOUT_item;
} ArgChooserModeChoiceItemsRec, *ArgChooserModeChoiceItems;
typedef struct {
    Widget	None_item;
    Widget	char_item;
    Widget	int_item;
} ArgChooserArgValTypeChoiceItemsRec, *ArgChooserArgValTypeChoiceItems;
typedef struct {
    Widget	IN_item;
    Widget	OUT_item;
    Widget	INOUT_item;
} ArgChooserModeChoiceMenuItemsRec, *ArgChooserModeChoiceMenuItems;
typedef struct {
    Widget	None_item;
    Widget	char_item;
    Widget	int_item;
} ArgChooserArgValTypeChoiceMenuItemsRec, *ArgChooserArgValTypeChoiceMenuItems;
typedef struct
{
    Boolean	initialized;
    
    Widget	argChooser;	/* object "argChooser" */
    Widget	argChooser_shellform;
    Widget	argChooser_panedwin;
    Widget	argChooser_form;
    
    Widget	dialog_button_panel;
    
    Widget	argPane_frame;	/* object "argPane" */
    Widget	argPane;
    
    Widget	modeChoice_rowcolumn;	/* object "modeChoice" */
    Widget	modeChoice_menu;
    Widget	modeChoice_label;
    Widget	modeChoice;
    ArgChooserModeChoiceItemsRec	modeChoice_items;
    
    Widget	vtypeText_rowcolumn;	/* object "vtypeText" */
    Widget	vtypeText_label;
    Widget	vtypeText;
    
    Widget	argValTypeChoice_rowcolumn;	/* object "argValTypeChoice" */
    Widget	argValTypeChoice_menu;
    Widget	argValTypeChoice_label;
    Widget	argValTypeChoice;
    ArgChooserArgValTypeChoiceItemsRec	argValTypeChoice_items;
    
    Widget	argIvalBox_rowcolumn;	/* object "argIvalBox" */
    Widget	argIvalBox_label;
    Widget	argIvalBox;
    
    Widget	argValText_scrolledwin;	/* object "argValText" */
    Widget	argValText;
    
    Widget	argChooserOkButton;
    Widget	argChooserCancelButton;
    Widget	argChooserHelpButton;
} DtbArgChooserArgChooserInfoRec, *DtbArgChooserArgChooserInfo;


extern DtbArgChooserArgChooserInfoRec dtb_arg_chooser_arg_chooser;

/*
 * Structure Clear Procedures: These set the fields to NULL
 */
int dtbArgChooserArgChooserInfo_clear(DtbArgChooserArgChooserInfo instance);

/*
 * Structure Initialization Procedures: These create the widgets
 */
int dtb_arg_chooser_arg_chooser_initialize(
    DtbArgChooserArgChooserInfo	instance,
    Widget	parent
);

/*
 * User Callbacks
 */
void argOkayed(
    Widget	widget,
    XtPointer	clientData,
    XtPointer	callData
);
void argHelp(
    Widget	widget,
    XtPointer	clientData,
    XtPointer	callData
);

/*
 * Connections
 */
void argChooser_argValTypeChoice_None_item_CB1(
    Widget	widget,
    XtPointer	clientData,
    XtPointer	callData
);
void argChooser_argValTypeChoice_char_item_CB1(
    Widget	widget,
    XtPointer	clientData,
    XtPointer	callData
);
void argChooser_argValTypeChoice_int_item_CB1(
    Widget	widget,
    XtPointer	clientData,
    XtPointer	callData
);
void argChooser_argChooserOkButton_CB1(
    Widget	widget,
    XtPointer	clientData,
    XtPointer	callData
);
void argChooser_argChooserCancelButton_CB1(
    Widget	widget,
    XtPointer	clientData,
    XtPointer	callData
);
void argChooser_argValTypeChoice_None_item_CB2(
    Widget	widget,
    XtPointer	clientData,
    XtPointer	callData
);
void argChooser_argValTypeChoice_int_item_CB2(
    Widget	widget,
    XtPointer	clientData,
    XtPointer	callData
);
void argChooser_argValTypeChoice_char_item_CB2(
    Widget	widget,
    XtPointer	clientData,
    XtPointer	callData
);
#endif /* _ARGCHOOSER_UI_H_ */
/*
 * CDE - Common Desktop Environment
 *
 * Copyright (c) 1993-2012, The Open Group. All rights reserved.
 *
 * These libraries and programs are free software; you can
 * redistribute them and/or modify them under the terms of the GNU
 * Lesser General Public License as published by the Free Software
 * Foundation; either version 2 of the License, or (at your option)
 * any later version.
 *
 * These libraries and programs are distributed in the hope that
 * they will be useful, but WITHOUT ANY WARRANTY; without even the
 * implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR
 * PURPOSE. See the GNU Lesser General Public License for more
 * details.
 *
 * You should have received a copy of the GNU Lesser General Public
 * License along with these libraries and programs; if not, write
 * to the Free Software Foundation, Inc., 51 Franklin Street, Fifth
 * Floor, Boston, MA 02110-1301 USA
 */
/* $XConsortium: closeBrace.h /main/3 1995/11/06 17:12:38 rswiston $ */
#ifdef	__cplusplus
}
#endif
