#!/usr/bin/ksh
dtdcbk_libdir=/home/matt/cdesktopenv-code/cde/programs/dtdocbook 	dtdcbk_libexecdir=/home/matt/cdesktopenv-code/cde/programs/dtdocbook 	dtdcbk_datarootdir=/home/matt/cdesktopenv-code/cde/programs/dtdocbook 	/usr/bin/ksh /home/matt/cdesktopenv-code/cde/programs/dtdocbook/doc_utils/../dtdocbook2sdl $@
