#include <EUSCompat.h>

/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#include <memory.h> /* for memset */
#include "rtable2.h"
#define access_none_2 0x0 /* owner only */
#define access_read_2 0x1
#define access_write_2 0x2
#define access_delete_2 0x4
#define access_exec_2 0x8 /* execution permission is a hack! */
#define VOIDPID -1 /* pre-V3 tools do present pids */

/* Default timeout can be changed using clnt_control() */
static struct timeval TIMEOUT = { 25, 0 };

void *
_DtCm_rtable_ping_2(void *argp, _DtCm_Connection *clnt)
{
	static char clnt_res;

	memset((char *)&clnt_res, 0, sizeof(clnt_res));
	if (_DtCm_clnt_call (clnt, rtable_ping,
		(xdrproc_t) xdr_void, (caddr_t) argp,
		(xdrproc_t) xdr_void, (caddr_t) &clnt_res,
		TIMEOUT) != RPC_SUCCESS) {
		return (NULL);
	}
	return ((void *)&clnt_res);
}

Table_Res_2 *
_DtCm_rtable_lookup_2(Table_Args_2 *argp, _DtCm_Connection *clnt)
{
	static Table_Res_2 clnt_res;

	memset((char *)&clnt_res, 0, sizeof(clnt_res));
	if (_DtCm_clnt_call (clnt, rtable_lookup,
		(xdrproc_t) _DtCm_xdr_Table_Args_2, (caddr_t) argp,
		(xdrproc_t) _DtCm_xdr_Table_Res_2, (caddr_t) &clnt_res,
		TIMEOUT) != RPC_SUCCESS) {
		return (NULL);
	}
	return (&clnt_res);
}

Table_Res_2 *
_DtCm_rtable_lookup_next_larger_2(Table_Args_2 *argp, _DtCm_Connection *clnt)
{
	static Table_Res_2 clnt_res;

	memset((char *)&clnt_res, 0, sizeof(clnt_res));
	if (_DtCm_clnt_call (clnt, rtable_lookup_next_larger,
		(xdrproc_t) _DtCm_xdr_Table_Args_2, (caddr_t) argp,
		(xdrproc_t) _DtCm_xdr_Table_Res_2, (caddr_t) &clnt_res,
		TIMEOUT) != RPC_SUCCESS) {
		return (NULL);
	}
	return (&clnt_res);
}

Table_Res_2 *
_DtCm_rtable_lookup_next_smaller_2(Table_Args_2 *argp, _DtCm_Connection *clnt)
{
	static Table_Res_2 clnt_res;

	memset((char *)&clnt_res, 0, sizeof(clnt_res));
	if (_DtCm_clnt_call (clnt, rtable_lookup_next_smaller,
		(xdrproc_t) _DtCm_xdr_Table_Args_2, (caddr_t) argp,
		(xdrproc_t) _DtCm_xdr_Table_Res_2, (caddr_t) &clnt_res,
		TIMEOUT) != RPC_SUCCESS) {
		return (NULL);
	}
	return (&clnt_res);
}

Table_Res_2 *
_DtCm_rtable_lookup_range_2(Table_Args_2 *argp, _DtCm_Connection *clnt)
{
	static Table_Res_2 clnt_res;

	memset((char *)&clnt_res, 0, sizeof(clnt_res));
	if (_DtCm_clnt_call (clnt, rtable_lookup_range,
		(xdrproc_t) _DtCm_xdr_Table_Args_2, (caddr_t) argp,
		(xdrproc_t) _DtCm_xdr_Table_Res_2, (caddr_t) &clnt_res,
		TIMEOUT) != RPC_SUCCESS) {
		return (NULL);
	}
	return (&clnt_res);
}

Table_Res_2 *
_DtCm_rtable_abbreviated_lookup_range_2(Table_Args_2 *argp, _DtCm_Connection *clnt)
{
	static Table_Res_2 clnt_res;

	memset((char *)&clnt_res, 0, sizeof(clnt_res));
	if (_DtCm_clnt_call (clnt, rtable_abbreviated_lookup_range,
		(xdrproc_t) _DtCm_xdr_Table_Args_2, (caddr_t) argp,
		(xdrproc_t) _DtCm_xdr_Table_Res_2, (caddr_t) &clnt_res,
		TIMEOUT) != RPC_SUCCESS) {
		return (NULL);
	}
	return (&clnt_res);
}

Table_Res_2 *
_DtCm_rtable_insert_2(Table_Args_2 *argp, _DtCm_Connection *clnt)
{
	static Table_Res_2 clnt_res;

	memset((char *)&clnt_res, 0, sizeof(clnt_res));
	if (_DtCm_clnt_call (clnt, rtable_insert,
		(xdrproc_t) _DtCm_xdr_Table_Args_2, (caddr_t) argp,
		(xdrproc_t) _DtCm_xdr_Table_Res_2, (caddr_t) &clnt_res,
		TIMEOUT) != RPC_SUCCESS) {
		return (NULL);
	}
	return (&clnt_res);
}

Table_Res_2 *
_DtCm_rtable_delete_2(Table_Args_2 *argp, _DtCm_Connection *clnt)
{
	static Table_Res_2 clnt_res;

	memset((char *)&clnt_res, 0, sizeof(clnt_res));
	if (_DtCm_clnt_call (clnt, rtable_delete,
		(xdrproc_t) _DtCm_xdr_Table_Args_2, (caddr_t) argp,
		(xdrproc_t) _DtCm_xdr_Table_Res_2, (caddr_t) &clnt_res,
		TIMEOUT) != RPC_SUCCESS) {
		return (NULL);
	}
	return (&clnt_res);
}

Table_Res_2 *
_DtCm_rtable_delete_instance_2(Table_Args_2 *argp, _DtCm_Connection *clnt)
{
	static Table_Res_2 clnt_res;

	memset((char *)&clnt_res, 0, sizeof(clnt_res));
	if (_DtCm_clnt_call (clnt, rtable_delete_instance,
		(xdrproc_t) _DtCm_xdr_Table_Args_2, (caddr_t) argp,
		(xdrproc_t) _DtCm_xdr_Table_Res_2, (caddr_t) &clnt_res,
		TIMEOUT) != RPC_SUCCESS) {
		return (NULL);
	}
	return (&clnt_res);
}

Table_Res_2 *
_DtCm_rtable_change_2(Table_Args_2 *argp, _DtCm_Connection *clnt)
{
	static Table_Res_2 clnt_res;

	memset((char *)&clnt_res, 0, sizeof(clnt_res));
	if (_DtCm_clnt_call (clnt, rtable_change,
		(xdrproc_t) _DtCm_xdr_Table_Args_2, (caddr_t) argp,
		(xdrproc_t) _DtCm_xdr_Table_Res_2, (caddr_t) &clnt_res,
		TIMEOUT) != RPC_SUCCESS) {
		return (NULL);
	}
	return (&clnt_res);
}

Table_Res_2 *
_DtCm_rtable_change_instance_2(Table_Args_2 *argp, _DtCm_Connection *clnt)
{
	static Table_Res_2 clnt_res;

	memset((char *)&clnt_res, 0, sizeof(clnt_res));
	if (_DtCm_clnt_call (clnt, rtable_change_instance,
		(xdrproc_t) _DtCm_xdr_Table_Args_2, (caddr_t) argp,
		(xdrproc_t) _DtCm_xdr_Table_Res_2, (caddr_t) &clnt_res,
		TIMEOUT) != RPC_SUCCESS) {
		return (NULL);
	}
	return (&clnt_res);
}

Table_Res_2 *
_DtCm_rtable_lookup_next_reminder_2(Table_Args_2 *argp, _DtCm_Connection *clnt)
{
	static Table_Res_2 clnt_res;

	memset((char *)&clnt_res, 0, sizeof(clnt_res));
	if (_DtCm_clnt_call (clnt, rtable_lookup_next_reminder,
		(xdrproc_t) _DtCm_xdr_Table_Args_2, (caddr_t) argp,
		(xdrproc_t) _DtCm_xdr_Table_Res_2, (caddr_t) &clnt_res,
		TIMEOUT) != RPC_SUCCESS) {
		return (NULL);
	}
	return (&clnt_res);
}

Table_Status_2 *
_DtCm_rtable_check_2(Table_Args_2 *argp, _DtCm_Connection *clnt)
{
	static Table_Status_2 clnt_res;

	memset((char *)&clnt_res, 0, sizeof(clnt_res));
	if (_DtCm_clnt_call (clnt, rtable_check,
		(xdrproc_t) _DtCm_xdr_Table_Args_2, (caddr_t) argp,
		(xdrproc_t) _DtCm_xdr_Table_Status_2, (caddr_t) &clnt_res,
		TIMEOUT) != RPC_SUCCESS) {
		return (NULL);
	}
	return (&clnt_res);
}

Table_Status_2 *
_DtCm_rtable_flush_table_2(Table_Args_2 *argp, _DtCm_Connection *clnt)
{
	static Table_Status_2 clnt_res;

	memset((char *)&clnt_res, 0, sizeof(clnt_res));
	if (_DtCm_clnt_call (clnt, rtable_flush_table,
		(xdrproc_t) _DtCm_xdr_Table_Args_2, (caddr_t) argp,
		(xdrproc_t) _DtCm_xdr_Table_Status_2, (caddr_t) &clnt_res,
		TIMEOUT) != RPC_SUCCESS) {
		return (NULL);
	}
	return (&clnt_res);
}

int *
_DtCm_rtable_size_2(Table_Args_2 *argp, _DtCm_Connection *clnt)
{
	static int clnt_res;

	memset((char *)&clnt_res, 0, sizeof(clnt_res));
	if (_DtCm_clnt_call (clnt, rtable_size,
		(xdrproc_t) _DtCm_xdr_Table_Args_2, (caddr_t) argp,
		(xdrproc_t) xdr_int, (caddr_t) &clnt_res,
		TIMEOUT) != RPC_SUCCESS) {
		return (NULL);
	}
	return (&clnt_res);
}

Registration_Status_2 *
_DtCm_register_callback_2(Registration_2 *argp, _DtCm_Connection *clnt)
{
	static Registration_Status_2 clnt_res;

	memset((char *)&clnt_res, 0, sizeof(clnt_res));
	if (_DtCm_clnt_call (clnt, register_callback,
		(xdrproc_t) _DtCm_xdr_Registration_2, (caddr_t) argp,
		(xdrproc_t) _DtCm_xdr_Registration_Status_2, (caddr_t) &clnt_res,
		TIMEOUT) != RPC_SUCCESS) {
		return (NULL);
	}
	return (&clnt_res);
}

Registration_Status_2 *
_DtCm_deregister_callback_2(Registration_2 *argp, _DtCm_Connection *clnt)
{
	static Registration_Status_2 clnt_res;

	memset((char *)&clnt_res, 0, sizeof(clnt_res));
	if (_DtCm_clnt_call (clnt, deregister_callback,
		(xdrproc_t) _DtCm_xdr_Registration_2, (caddr_t) argp,
		(xdrproc_t) _DtCm_xdr_Registration_Status_2, (caddr_t) &clnt_res,
		TIMEOUT) != RPC_SUCCESS) {
		return (NULL);
	}
	return (&clnt_res);
}

Access_Status_2 *
_DtCm_rtable_set_access_2(Access_Args_2 *argp, _DtCm_Connection *clnt)
{
	static Access_Status_2 clnt_res;

	memset((char *)&clnt_res, 0, sizeof(clnt_res));
	if (_DtCm_clnt_call (clnt, rtable_set_access,
		(xdrproc_t) _DtCm_xdr_Access_Args_2, (caddr_t) argp,
		(xdrproc_t) _DtCm_xdr_Access_Status_2, (caddr_t) &clnt_res,
		TIMEOUT) != RPC_SUCCESS) {
		return (NULL);
	}
	return (&clnt_res);
}

Access_Args_2 *
_DtCm_rtable_get_access_2(Access_Args_2 *argp, _DtCm_Connection *clnt)
{
	static Access_Args_2 clnt_res;

	memset((char *)&clnt_res, 0, sizeof(clnt_res));
	if (_DtCm_clnt_call (clnt, rtable_get_access,
		(xdrproc_t) _DtCm_xdr_Access_Args_2, (caddr_t) argp,
		(xdrproc_t) _DtCm_xdr_Access_Args_2, (caddr_t) &clnt_res,
		TIMEOUT) != RPC_SUCCESS) {
		return (NULL);
	}
	return (&clnt_res);
}
