#include <EUSCompat.h>

/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#include "rtable3.h"

bool_t
_DtCm_xdr_Buffer_3 (XDR *xdrs, Buffer_3 *objp)
{
	register int32_t *buf;

	 if (!xdr_string (xdrs, objp, ~0))
		 return FALSE;
	return TRUE;
}

bool_t
_DtCm_xdr_Transaction_3 (XDR *xdrs, Transaction_3 *objp)
{
	register int32_t *buf;

	 if (!xdr_enum (xdrs, (enum_t *) objp))
		 return FALSE;
	return TRUE;
}

bool_t
_DtCm_xdr_Interval_3 (XDR *xdrs, Interval_3 *objp)
{
	register int32_t *buf;

	 if (!xdr_enum (xdrs, (enum_t *) objp))
		 return FALSE;
	return TRUE;
}

bool_t
_DtCm_xdr_Period_3 (XDR *xdrs, Period_3 *objp)
{
	register int32_t *buf;

	 if (!_DtCm_xdr_Interval_3 (xdrs, &objp->period))
		 return FALSE;
	 if (!xdr_int (xdrs, &objp->nth))
		 return FALSE;
	return TRUE;
}

bool_t
_DtCm_xdr_Event_Type_3 (XDR *xdrs, Event_Type_3 *objp)
{
	register int32_t *buf;

	 if (!xdr_enum (xdrs, (enum_t *) objp))
		 return FALSE;
	return TRUE;
}

bool_t
_DtCm_xdr_Tag_3 (XDR *xdrs, Tag_3 *objp)
{
	register int32_t *buf;

	 if (!_DtCm_xdr_Event_Type_3 (xdrs, &objp->tag))
		 return FALSE;
	 if (!xdr_int (xdrs, &objp->showtime))
		 return FALSE;
	 if (!xdr_pointer (xdrs, (char **)&objp->next, sizeof (Tag_3), (xdrproc_t) _DtCm_xdr_Tag_3))
		 return FALSE;
	return TRUE;
}

bool_t
_DtCm_xdr_Privacy_Level_3 (XDR *xdrs, Privacy_Level_3 *objp)
{
	register int32_t *buf;

	 if (!xdr_enum (xdrs, (enum_t *) objp))
		 return FALSE;
	return TRUE;
}

bool_t
_DtCm_xdr_Attribute_3 (XDR *xdrs, Attribute_3 *objp)
{
	register int32_t *buf;

	 if (!xdr_pointer (xdrs, (char **)&objp->next, sizeof (Attribute_3), (xdrproc_t) _DtCm_xdr_Attribute_3))
		 return FALSE;
	 if (!_DtCm_xdr_Buffer_3 (xdrs, &objp->attr))
		 return FALSE;
	 if (!_DtCm_xdr_Buffer_3 (xdrs, &objp->value))
		 return FALSE;
	 if (!_DtCm_xdr_Buffer_3 (xdrs, &objp->clientdata))
		 return FALSE;
	return TRUE;
}

bool_t
_DtCm_xdr_Attr_3 (XDR *xdrs, Attr_3 *objp)
{
	register int32_t *buf;

	 if (!xdr_pointer (xdrs, (char **)objp, sizeof (Attribute_3), (xdrproc_t) _DtCm_xdr_Attribute_3))
		 return FALSE;
	return TRUE;
}

bool_t
_DtCm_xdr_Except_3 (XDR *xdrs, Except_3 *objp)
{
	register int32_t *buf;

	 if (!xdr_int (xdrs, &objp->ordinal))
		 return FALSE;
	 if (!xdr_pointer (xdrs, (char **)&objp->next, sizeof (Except_3), (xdrproc_t) _DtCm_xdr_Except_3))
		 return FALSE;
	return TRUE;
}

bool_t
_DtCm_xdr_Exception_3 (XDR *xdrs, Exception_3 *objp)
{
	register int32_t *buf;

	 if (!xdr_pointer (xdrs, (char **)objp, sizeof (Except_3), (xdrproc_t) _DtCm_xdr_Except_3))
		 return FALSE;
	return TRUE;
}

bool_t
_DtCm_xdr_Id_3 (XDR *xdrs, Id_3 *objp)
{
	register int32_t *buf;

	 if (!xdr_time_t (xdrs, &objp->tick))
		 return FALSE;
	 if (!xdr_long (xdrs, &objp->key))
		 return FALSE;
	return TRUE;
}

bool_t
_DtCm_xdr_Uid_3 (XDR *xdrs, Uid_3 *objp)
{
	register int32_t *buf;

	 if (!_DtCm_xdr_Id_3 (xdrs, &objp->appt_id))
		 return FALSE;
	 if (!xdr_pointer (xdrs, (char **)&objp->next, sizeof (Uid_3), (xdrproc_t) _DtCm_xdr_Uid_3))
		 return FALSE;
	return TRUE;
}

bool_t
_DtCm_xdr_Appt_Status_3 (XDR *xdrs, Appt_Status_3 *objp)
{
	register int32_t *buf;

	 if (!xdr_enum (xdrs, (enum_t *) objp))
		 return FALSE;
	return TRUE;
}

bool_t
_DtCm_xdr_Appt_3 (XDR *xdrs, Appt_3 *objp)
{
	register int32_t *buf;

	 if (!_DtCm_xdr_Id_3 (xdrs, &objp->appt_id))
		 return FALSE;
	 if (!xdr_pointer (xdrs, (char **)&objp->tag, sizeof (Tag_3), (xdrproc_t) _DtCm_xdr_Tag_3))
		 return FALSE;
	 if (!xdr_int (xdrs, &objp->duration))
		 return FALSE;
	 if (!xdr_int (xdrs, &objp->ntimes))
		 return FALSE;
	 if (!_DtCm_xdr_Buffer_3 (xdrs, &objp->what))
		 return FALSE;
	 if (!_DtCm_xdr_Period_3 (xdrs, &objp->period))
		 return FALSE;
	 if (!_DtCm_xdr_Buffer_3 (xdrs, &objp->author))
		 return FALSE;
	 if (!_DtCm_xdr_Buffer_3 (xdrs, &objp->client_data))
		 return FALSE;
	 if (!xdr_pointer (xdrs, (char **)&objp->exception, sizeof (Except_3), (xdrproc_t) _DtCm_xdr_Except_3))
		 return FALSE;
	 if (!xdr_pointer (xdrs, (char **)&objp->attr, sizeof (Attribute_3), (xdrproc_t) _DtCm_xdr_Attribute_3))
		 return FALSE;
	 if (!_DtCm_xdr_Appt_Status_3 (xdrs, &objp->appt_status))
		 return FALSE;
	 if (!_DtCm_xdr_Privacy_Level_3 (xdrs, &objp->privacy))
		 return FALSE;
	 if (!xdr_pointer (xdrs, (char **)&objp->next, sizeof (Appt_3), (xdrproc_t) _DtCm_xdr_Appt_3))
		 return FALSE;
	return TRUE;
}

bool_t
_DtCm_xdr_Abb_Appt_3 (XDR *xdrs, Abb_Appt_3 *objp)
{
	register int32_t *buf;

	 if (!_DtCm_xdr_Id_3 (xdrs, &objp->appt_id))
		 return FALSE;
	 if (!xdr_pointer (xdrs, (char **)&objp->tag, sizeof (Tag_3), (xdrproc_t) _DtCm_xdr_Tag_3))
		 return FALSE;
	 if (!_DtCm_xdr_Buffer_3 (xdrs, &objp->what))
		 return FALSE;
	 if (!xdr_int (xdrs, &objp->duration))
		 return FALSE;
	 if (!_DtCm_xdr_Period_3 (xdrs, &objp->period))
		 return FALSE;
	 if (!xdr_pointer (xdrs, (char **)&objp->next, sizeof (Abb_Appt_3), (xdrproc_t) _DtCm_xdr_Abb_Appt_3))
		 return FALSE;
	 if (!_DtCm_xdr_Appt_Status_3 (xdrs, &objp->appt_status))
		 return FALSE;
	 if (!_DtCm_xdr_Privacy_Level_3 (xdrs, &objp->privacy))
		 return FALSE;
	return TRUE;
}

bool_t
_DtCm_xdr_Apptid_3 (XDR *xdrs, Apptid_3 *objp)
{
	register int32_t *buf;

	 if (!xdr_pointer (xdrs, (char **)&objp->oid, sizeof (Id_3), (xdrproc_t) _DtCm_xdr_Id_3))
		 return FALSE;
	 if (!xdr_pointer (xdrs, (char **)&objp->new_appt, sizeof (Appt_3), (xdrproc_t) _DtCm_xdr_Appt_3))
		 return FALSE;
	return TRUE;
}

bool_t
_DtCm_xdr_Reminder_3 (XDR *xdrs, Reminder_3 *objp)
{
	register int32_t *buf;

	 if (!_DtCm_xdr_Id_3 (xdrs, &objp->appt_id))
		 return FALSE;
	 if (!xdr_time_t (xdrs, &objp->tick))
		 return FALSE;
	 if (!_DtCm_xdr_Attribute_3 (xdrs, &objp->attr))
		 return FALSE;
	 if (!xdr_pointer (xdrs, (char **)&objp->next, sizeof (Reminder_3), (xdrproc_t) _DtCm_xdr_Reminder_3))
		 return FALSE;
	return TRUE;
}

bool_t
_DtCm_xdr_Table_Res_Type_3 (XDR *xdrs, Table_Res_Type_3 *objp)
{
	register int32_t *buf;

	 if (!xdr_enum (xdrs, (enum_t *) objp))
		 return FALSE;
	return TRUE;
}

bool_t
_DtCm_xdr_Table_Res_List_3 (XDR *xdrs, Table_Res_List_3 *objp)
{
	register int32_t *buf;

	 if (!_DtCm_xdr_Table_Res_Type_3 (xdrs, &objp->tag))
		 return FALSE;
	switch (objp->tag) {
	case AP_3:
		 if (!xdr_pointer (xdrs, (char **)&objp->Table_Res_List_3_u.a, sizeof (Appt_3), (xdrproc_t) _DtCm_xdr_Appt_3))
			 return FALSE;
		break;
	case RM_3:
		 if (!xdr_pointer (xdrs, (char **)&objp->Table_Res_List_3_u.r, sizeof (Reminder_3), (xdrproc_t) _DtCm_xdr_Reminder_3))
			 return FALSE;
		break;
	case AB_3:
		 if (!xdr_pointer (xdrs, (char **)&objp->Table_Res_List_3_u.b, sizeof (Abb_Appt_3), (xdrproc_t) _DtCm_xdr_Abb_Appt_3))
			 return FALSE;
		break;
	case ID_3:
		 if (!xdr_pointer (xdrs, (char **)&objp->Table_Res_List_3_u.i, sizeof (Uid_3), (xdrproc_t) _DtCm_xdr_Uid_3))
			 return FALSE;
		break;
	default:
		break;
	}
	return TRUE;
}

bool_t
_DtCm_xdr_Access_Status_3 (XDR *xdrs, Access_Status_3 *objp)
{
	register int32_t *buf;

	 if (!xdr_enum (xdrs, (enum_t *) objp))
		 return FALSE;
	return TRUE;
}

bool_t
_DtCm_xdr_Table_Res_3 (XDR *xdrs, Table_Res_3 *objp)
{
	register int32_t *buf;

	 if (!_DtCm_xdr_Access_Status_3 (xdrs, &objp->status))
		 return FALSE;
	 if (!_DtCm_xdr_Table_Res_List_3 (xdrs, &objp->res))
		 return FALSE;
	return TRUE;
}
#define access_none_3 0x0 /* owner only */
#define access_read_3 0x1
#define access_write_3 0x2
#define access_delete_3 0x4
#define access_exec_3 0x8 /* execution permission is a hack! */

bool_t
_DtCm_xdr_Access_Entry_3 (XDR *xdrs, Access_Entry_3 *objp)
{
	register int32_t *buf;

	 if (!_DtCm_xdr_Buffer_3 (xdrs, &objp->who))
		 return FALSE;
	 if (!xdr_int (xdrs, &objp->access_type))
		 return FALSE;
	 if (!xdr_pointer (xdrs, (char **)&objp->next, sizeof (Access_Entry_3), (xdrproc_t) _DtCm_xdr_Access_Entry_3))
		 return FALSE;
	return TRUE;
}

bool_t
_DtCm_xdr_Access_Args_3 (XDR *xdrs, Access_Args_3 *objp)
{
	register int32_t *buf;

	 if (!_DtCm_xdr_Buffer_3 (xdrs, &objp->target))
		 return FALSE;
	 if (!xdr_pointer (xdrs, (char **)&objp->access_list, sizeof (Access_Entry_3), (xdrproc_t) _DtCm_xdr_Access_Entry_3))
		 return FALSE;
	return TRUE;
}

bool_t
_DtCm_xdr_Range_3 (XDR *xdrs, Range_3 *objp)
{
	register int32_t *buf;

	 if (!xdr_time_t (xdrs, &objp->key1))
		 return FALSE;
	 if (!xdr_time_t (xdrs, &objp->key2))
		 return FALSE;
	 if (!xdr_pointer (xdrs, (char **)&objp->next, sizeof (Range_3), (xdrproc_t) _DtCm_xdr_Range_3))
		 return FALSE;
	return TRUE;
}

bool_t
_DtCm_xdr_Keyrange_3 (XDR *xdrs, Keyrange_3 *objp)
{
	register int32_t *buf;

	 if (!xdr_long (xdrs, &objp->key))
		 return FALSE;
	 if (!xdr_time_t (xdrs, &objp->tick1))
		 return FALSE;
	 if (!xdr_time_t (xdrs, &objp->tick2))
		 return FALSE;
	 if (!xdr_pointer (xdrs, (char **)&objp->next, sizeof (Keyrange_3), (xdrproc_t) _DtCm_xdr_Keyrange_3))
		 return FALSE;
	return TRUE;
}

bool_t
_DtCm_xdr_Table_Args_Type_3 (XDR *xdrs, Table_Args_Type_3 *objp)
{
	register int32_t *buf;

	 if (!xdr_enum (xdrs, (enum_t *) objp))
		 return FALSE;
	return TRUE;
}

bool_t
_DtCm_xdr_Args_3 (XDR *xdrs, Args_3 *objp)
{
	register int32_t *buf;

	 if (!_DtCm_xdr_Table_Args_Type_3 (xdrs, &objp->tag))
		 return FALSE;
	switch (objp->tag) {
	case TICK_3:
		 if (!xdr_time_t (xdrs, &objp->Args_3_u.tick))
			 return FALSE;
		break;
	case APPTID_3:
		 if (!_DtCm_xdr_Apptid_3 (xdrs, &objp->Args_3_u.apptid))
			 return FALSE;
		break;
	case UID_3:
		 if (!xdr_pointer (xdrs, (char **)&objp->Args_3_u.key, sizeof (Uid_3), (xdrproc_t) _DtCm_xdr_Uid_3))
			 return FALSE;
		break;
	case APPT_3:
		 if (!xdr_pointer (xdrs, (char **)&objp->Args_3_u.appt, sizeof (Appt_3), (xdrproc_t) _DtCm_xdr_Appt_3))
			 return FALSE;
		break;
	case RANGE_3:
		 if (!xdr_pointer (xdrs, (char **)&objp->Args_3_u.range, sizeof (Range_3), (xdrproc_t) _DtCm_xdr_Range_3))
			 return FALSE;
		break;
	case KEYRANGE_3:
		 if (!xdr_pointer (xdrs, (char **)&objp->Args_3_u.keyrange, sizeof (Keyrange_3), (xdrproc_t) _DtCm_xdr_Keyrange_3))
			 return FALSE;
		break;
	default:
		return FALSE;
	}
	return TRUE;
}

bool_t
_DtCm_xdr_Table_Args_3 (XDR *xdrs, Table_Args_3 *objp)
{
	register int32_t *buf;

	 if (!_DtCm_xdr_Buffer_3 (xdrs, &objp->target))
		 return FALSE;
	 if (!_DtCm_xdr_Args_3 (xdrs, &objp->args))
		 return FALSE;
	 if (!xdr_int (xdrs, &objp->pid))
		 return FALSE;
	return TRUE;
}

bool_t
_DtCm_xdr_Registration_3 (XDR *xdrs, Registration_3 *objp)
{
	register int32_t *buf;


	if (xdrs->x_op == XDR_ENCODE) {
		 if (!_DtCm_xdr_Buffer_3 (xdrs, &objp->target))
			 return FALSE;
		buf = XDR_INLINE (xdrs, 3 * BYTES_PER_XDR_UNIT);
		if (buf == NULL) {
			 if (!xdr_u_long (xdrs, &objp->prognum))
				 return FALSE;
			 if (!xdr_u_long (xdrs, &objp->versnum))
				 return FALSE;
			 if (!xdr_u_long (xdrs, &objp->procnum))
				 return FALSE;

		} else {
		IXDR_PUT_U_LONG(buf, objp->prognum);
		IXDR_PUT_U_LONG(buf, objp->versnum);
		IXDR_PUT_U_LONG(buf, objp->procnum);
		}
		 if (!xdr_pointer (xdrs, (char **)&objp->next, sizeof (Registration_3), (xdrproc_t) _DtCm_xdr_Registration_3))
			 return FALSE;
		 if (!xdr_int (xdrs, &objp->pid))
			 return FALSE;
		return TRUE;
	} else if (xdrs->x_op == XDR_DECODE) {
		 if (!_DtCm_xdr_Buffer_3 (xdrs, &objp->target))
			 return FALSE;
		buf = XDR_INLINE (xdrs, 3 * BYTES_PER_XDR_UNIT);
		if (buf == NULL) {
			 if (!xdr_u_long (xdrs, &objp->prognum))
				 return FALSE;
			 if (!xdr_u_long (xdrs, &objp->versnum))
				 return FALSE;
			 if (!xdr_u_long (xdrs, &objp->procnum))
				 return FALSE;

		} else {
		objp->prognum = IXDR_GET_U_LONG(buf);
		objp->versnum = IXDR_GET_U_LONG(buf);
		objp->procnum = IXDR_GET_U_LONG(buf);
		}
		 if (!xdr_pointer (xdrs, (char **)&objp->next, sizeof (Registration_3), (xdrproc_t) _DtCm_xdr_Registration_3))
			 return FALSE;
		 if (!xdr_int (xdrs, &objp->pid))
			 return FALSE;
	 return TRUE;
	}

	 if (!_DtCm_xdr_Buffer_3 (xdrs, &objp->target))
		 return FALSE;
	 if (!xdr_u_long (xdrs, &objp->prognum))
		 return FALSE;
	 if (!xdr_u_long (xdrs, &objp->versnum))
		 return FALSE;
	 if (!xdr_u_long (xdrs, &objp->procnum))
		 return FALSE;
	 if (!xdr_pointer (xdrs, (char **)&objp->next, sizeof (Registration_3), (xdrproc_t) _DtCm_xdr_Registration_3))
		 return FALSE;
	 if (!xdr_int (xdrs, &objp->pid))
		 return FALSE;
	return TRUE;
}

bool_t
_DtCm_xdr_Table_Status_3 (XDR *xdrs, Table_Status_3 *objp)
{
	register int32_t *buf;

	 if (!xdr_enum (xdrs, (enum_t *) objp))
		 return FALSE;
	return TRUE;
}

bool_t
_DtCm_xdr_Registration_Status_3 (XDR *xdrs, Registration_Status_3 *objp)
{
	register int32_t *buf;

	 if (!xdr_enum (xdrs, (enum_t *) objp))
		 return FALSE;
	return TRUE;
}
