#include <EUSCompat.h>

/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#include <memory.h> /* for memset */
#include "rtable4.h"
#define access_none_4 0x0 /* owner only */
#define access_read_4 0x1
#define access_write_4 0x2
#define access_delete_4 0x4
#define access_exec_4 0x8 /* execution permission is a hack! */
#define WORLD "world" /* special user */

/*
 * rtable_delete and rtable_change take over the functionality of
 * rtable_delete_instance and rtable_change_instance repectively.
 * rtable_delete_instance and rtable_change_instance are now dummy
 * routines exist for backward compatibility purpose and return
 * access_notsupported.
 */

/* Default timeout can be changed using clnt_control() */
static struct timeval TIMEOUT = { 25, 0 };

void *
_DtCm_rtable_ping_4(void *argp, _DtCm_Connection *clnt)
{
	static char clnt_res;

	memset((char *)&clnt_res, 0, sizeof(clnt_res));
	if (_DtCm_clnt_call (clnt, rtable_ping,
		(xdrproc_t) xdr_void, (caddr_t) argp,
		(xdrproc_t) xdr_void, (caddr_t) &clnt_res,
		TIMEOUT) != RPC_SUCCESS) {
		return (NULL);
	}
	return ((void *)&clnt_res);
}

Table_Res_4 *
_DtCm_rtable_lookup_4(Table_Args_4 *argp, _DtCm_Connection *clnt)
{
	static Table_Res_4 clnt_res;

	memset((char *)&clnt_res, 0, sizeof(clnt_res));
	if (_DtCm_clnt_call (clnt, rtable_lookup,
		(xdrproc_t) _DtCm_xdr_Table_Args_4, (caddr_t) argp,
		(xdrproc_t) _DtCm_xdr_Table_Res_4, (caddr_t) &clnt_res,
		TIMEOUT) != RPC_SUCCESS) {
		return (NULL);
	}
	return (&clnt_res);
}

Table_Res_4 *
_DtCm_rtable_lookup_next_larger_4(Table_Args_4 *argp, _DtCm_Connection *clnt)
{
	static Table_Res_4 clnt_res;

	memset((char *)&clnt_res, 0, sizeof(clnt_res));
	if (_DtCm_clnt_call (clnt, rtable_lookup_next_larger,
		(xdrproc_t) _DtCm_xdr_Table_Args_4, (caddr_t) argp,
		(xdrproc_t) _DtCm_xdr_Table_Res_4, (caddr_t) &clnt_res,
		TIMEOUT) != RPC_SUCCESS) {
		return (NULL);
	}
	return (&clnt_res);
}

Table_Res_4 *
_DtCm_rtable_lookup_next_smaller_4(Table_Args_4 *argp, _DtCm_Connection *clnt)
{
	static Table_Res_4 clnt_res;

	memset((char *)&clnt_res, 0, sizeof(clnt_res));
	if (_DtCm_clnt_call (clnt, rtable_lookup_next_smaller,
		(xdrproc_t) _DtCm_xdr_Table_Args_4, (caddr_t) argp,
		(xdrproc_t) _DtCm_xdr_Table_Res_4, (caddr_t) &clnt_res,
		TIMEOUT) != RPC_SUCCESS) {
		return (NULL);
	}
	return (&clnt_res);
}

Table_Res_4 *
_DtCm_rtable_lookup_range_4(Table_Args_4 *argp, _DtCm_Connection *clnt)
{
	static Table_Res_4 clnt_res;

	memset((char *)&clnt_res, 0, sizeof(clnt_res));
	if (_DtCm_clnt_call (clnt, rtable_lookup_range,
		(xdrproc_t) _DtCm_xdr_Table_Args_4, (caddr_t) argp,
		(xdrproc_t) _DtCm_xdr_Table_Res_4, (caddr_t) &clnt_res,
		TIMEOUT) != RPC_SUCCESS) {
		return (NULL);
	}
	return (&clnt_res);
}

Table_Res_4 *
_DtCm_rtable_abbreviated_lookup_range_4(Table_Args_4 *argp, _DtCm_Connection *clnt)
{
	static Table_Res_4 clnt_res;

	memset((char *)&clnt_res, 0, sizeof(clnt_res));
	if (_DtCm_clnt_call (clnt, rtable_abbreviated_lookup_range,
		(xdrproc_t) _DtCm_xdr_Table_Args_4, (caddr_t) argp,
		(xdrproc_t) _DtCm_xdr_Table_Res_4, (caddr_t) &clnt_res,
		TIMEOUT) != RPC_SUCCESS) {
		return (NULL);
	}
	return (&clnt_res);
}

Table_Res_4 *
_DtCm_rtable_insert_4(Table_Args_4 *argp, _DtCm_Connection *clnt)
{
	static Table_Res_4 clnt_res;

	memset((char *)&clnt_res, 0, sizeof(clnt_res));
	if (_DtCm_clnt_call (clnt, rtable_insert,
		(xdrproc_t) _DtCm_xdr_Table_Args_4, (caddr_t) argp,
		(xdrproc_t) _DtCm_xdr_Table_Res_4, (caddr_t) &clnt_res,
		TIMEOUT) != RPC_SUCCESS) {
		return (NULL);
	}
	return (&clnt_res);
}

Table_Res_4 *
_DtCm_rtable_delete_4(Table_Args_4 *argp, _DtCm_Connection *clnt)
{
	static Table_Res_4 clnt_res;

	memset((char *)&clnt_res, 0, sizeof(clnt_res));
	if (_DtCm_clnt_call (clnt, rtable_delete,
		(xdrproc_t) _DtCm_xdr_Table_Args_4, (caddr_t) argp,
		(xdrproc_t) _DtCm_xdr_Table_Res_4, (caddr_t) &clnt_res,
		TIMEOUT) != RPC_SUCCESS) {
		return (NULL);
	}
	return (&clnt_res);
}

Table_Res_4 *
_DtCm_rtable_delete_instance_4(Table_Args_4 *argp, _DtCm_Connection *clnt)
{
	static Table_Res_4 clnt_res;

	memset((char *)&clnt_res, 0, sizeof(clnt_res));
	if (_DtCm_clnt_call (clnt, rtable_delete_instance,
		(xdrproc_t) _DtCm_xdr_Table_Args_4, (caddr_t) argp,
		(xdrproc_t) _DtCm_xdr_Table_Res_4, (caddr_t) &clnt_res,
		TIMEOUT) != RPC_SUCCESS) {
		return (NULL);
	}
	return (&clnt_res);
}

Table_Res_4 *
_DtCm_rtable_change_4(Table_Args_4 *argp, _DtCm_Connection *clnt)
{
	static Table_Res_4 clnt_res;

	memset((char *)&clnt_res, 0, sizeof(clnt_res));
	if (_DtCm_clnt_call (clnt, rtable_change,
		(xdrproc_t) _DtCm_xdr_Table_Args_4, (caddr_t) argp,
		(xdrproc_t) _DtCm_xdr_Table_Res_4, (caddr_t) &clnt_res,
		TIMEOUT) != RPC_SUCCESS) {
		return (NULL);
	}
	return (&clnt_res);
}

Table_Res_4 *
_DtCm_rtable_change_instance_4(Table_Args_4 *argp, _DtCm_Connection *clnt)
{
	static Table_Res_4 clnt_res;

	memset((char *)&clnt_res, 0, sizeof(clnt_res));
	if (_DtCm_clnt_call (clnt, rtable_change_instance,
		(xdrproc_t) _DtCm_xdr_Table_Args_4, (caddr_t) argp,
		(xdrproc_t) _DtCm_xdr_Table_Res_4, (caddr_t) &clnt_res,
		TIMEOUT) != RPC_SUCCESS) {
		return (NULL);
	}
	return (&clnt_res);
}

Table_Res_4 *
_DtCm_rtable_lookup_next_reminder_4(Table_Args_4 *argp, _DtCm_Connection *clnt)
{
	static Table_Res_4 clnt_res;

	memset((char *)&clnt_res, 0, sizeof(clnt_res));
	if (_DtCm_clnt_call (clnt, rtable_lookup_next_reminder,
		(xdrproc_t) _DtCm_xdr_Table_Args_4, (caddr_t) argp,
		(xdrproc_t) _DtCm_xdr_Table_Res_4, (caddr_t) &clnt_res,
		TIMEOUT) != RPC_SUCCESS) {
		return (NULL);
	}
	return (&clnt_res);
}

Table_Status_4 *
_DtCm_rtable_check_4(Table_Args_4 *argp, _DtCm_Connection *clnt)
{
	static Table_Status_4 clnt_res;

	memset((char *)&clnt_res, 0, sizeof(clnt_res));
	if (_DtCm_clnt_call (clnt, rtable_check,
		(xdrproc_t) _DtCm_xdr_Table_Args_4, (caddr_t) argp,
		(xdrproc_t) _DtCm_xdr_Table_Status_4, (caddr_t) &clnt_res,
		TIMEOUT) != RPC_SUCCESS) {
		return (NULL);
	}
	return (&clnt_res);
}

Table_Status_4 *
_DtCm_rtable_flush_table_4(Table_Args_4 *argp, _DtCm_Connection *clnt)
{
	static Table_Status_4 clnt_res;

	memset((char *)&clnt_res, 0, sizeof(clnt_res));
	if (_DtCm_clnt_call (clnt, rtable_flush_table,
		(xdrproc_t) _DtCm_xdr_Table_Args_4, (caddr_t) argp,
		(xdrproc_t) _DtCm_xdr_Table_Status_4, (caddr_t) &clnt_res,
		TIMEOUT) != RPC_SUCCESS) {
		return (NULL);
	}
	return (&clnt_res);
}

int *
_DtCm_rtable_size_4(Table_Args_4 *argp, _DtCm_Connection *clnt)
{
	static int clnt_res;

	memset((char *)&clnt_res, 0, sizeof(clnt_res));
	if (_DtCm_clnt_call (clnt, rtable_size,
		(xdrproc_t) _DtCm_xdr_Table_Args_4, (caddr_t) argp,
		(xdrproc_t) xdr_int, (caddr_t) &clnt_res,
		TIMEOUT) != RPC_SUCCESS) {
		return (NULL);
	}
	return (&clnt_res);
}

Registration_Status_4 *
_DtCm_register_callback_4(Registration_4 *argp, _DtCm_Connection *clnt)
{
	static Registration_Status_4 clnt_res;

	memset((char *)&clnt_res, 0, sizeof(clnt_res));
	if (_DtCm_clnt_call (clnt, register_callback,
		(xdrproc_t) _DtCm_xdr_Registration_4, (caddr_t) argp,
		(xdrproc_t) _DtCm_xdr_Registration_Status_4, (caddr_t) &clnt_res,
		TIMEOUT) != RPC_SUCCESS) {
		return (NULL);
	}
	return (&clnt_res);
}

Registration_Status_4 *
_DtCm_deregister_callback_4(Registration_4 *argp, _DtCm_Connection *clnt)
{
	static Registration_Status_4 clnt_res;

	memset((char *)&clnt_res, 0, sizeof(clnt_res));
	if (_DtCm_clnt_call (clnt, deregister_callback,
		(xdrproc_t) _DtCm_xdr_Registration_4, (caddr_t) argp,
		(xdrproc_t) _DtCm_xdr_Registration_Status_4, (caddr_t) &clnt_res,
		TIMEOUT) != RPC_SUCCESS) {
		return (NULL);
	}
	return (&clnt_res);
}

Access_Status_4 *
_DtCm_rtable_set_access_4(Access_Args_4 *argp, _DtCm_Connection *clnt)
{
	static Access_Status_4 clnt_res;

	memset((char *)&clnt_res, 0, sizeof(clnt_res));
	if (_DtCm_clnt_call (clnt, rtable_set_access,
		(xdrproc_t) _DtCm_xdr_Access_Args_4, (caddr_t) argp,
		(xdrproc_t) _DtCm_xdr_Access_Status_4, (caddr_t) &clnt_res,
		TIMEOUT) != RPC_SUCCESS) {
		return (NULL);
	}
	return (&clnt_res);
}

Access_Args_4 *
_DtCm_rtable_get_access_4(Access_Args_4 *argp, _DtCm_Connection *clnt)
{
	static Access_Args_4 clnt_res;

	memset((char *)&clnt_res, 0, sizeof(clnt_res));
	if (_DtCm_clnt_call (clnt, rtable_get_access,
		(xdrproc_t) _DtCm_xdr_Access_Args_4, (caddr_t) argp,
		(xdrproc_t) _DtCm_xdr_Access_Args_4, (caddr_t) &clnt_res,
		TIMEOUT) != RPC_SUCCESS) {
		return (NULL);
	}
	return (&clnt_res);
}

Table_Res_4 *
_DtCm_rtable_abbreviated_lookup_key_range_4(Table_Args_4 *argp, _DtCm_Connection *clnt)
{
	static Table_Res_4 clnt_res;

	memset((char *)&clnt_res, 0, sizeof(clnt_res));
	if (_DtCm_clnt_call (clnt, rtable_abbreviated_lookup_key_range,
		(xdrproc_t) _DtCm_xdr_Table_Args_4, (caddr_t) argp,
		(xdrproc_t) _DtCm_xdr_Table_Res_4, (caddr_t) &clnt_res,
		TIMEOUT) != RPC_SUCCESS) {
		return (NULL);
	}
	return (&clnt_res);
}

long *
_DtCm_rtable_gmtoff_4(void *argp, _DtCm_Connection *clnt)
{
	static long clnt_res;

	memset((char *)&clnt_res, 0, sizeof(clnt_res));
	if (_DtCm_clnt_call (clnt, rtable_gmtoff,
		(xdrproc_t) xdr_void, (caddr_t) argp,
		(xdrproc_t) xdr_long, (caddr_t) &clnt_res,
		TIMEOUT) != RPC_SUCCESS) {
		return (NULL);
	}
	return (&clnt_res);
}

Table_Status_4 *
_DtCm_rtable_create_4(Table_Op_Args_4 *argp, _DtCm_Connection *clnt)
{
	static Table_Status_4 clnt_res;

	memset((char *)&clnt_res, 0, sizeof(clnt_res));
	if (_DtCm_clnt_call (clnt, rtable_create,
		(xdrproc_t) _DtCm_xdr_Table_Op_Args_4, (caddr_t) argp,
		(xdrproc_t) _DtCm_xdr_Table_Status_4, (caddr_t) &clnt_res,
		TIMEOUT) != RPC_SUCCESS) {
		return (NULL);
	}
	return (&clnt_res);
}

Table_Status_4 *
_DtCm_rtable_remove_4(Table_Op_Args_4 *argp, _DtCm_Connection *clnt)
{
	static Table_Status_4 clnt_res;

	memset((char *)&clnt_res, 0, sizeof(clnt_res));
	if (_DtCm_clnt_call (clnt, rtable_remove,
		(xdrproc_t) _DtCm_xdr_Table_Op_Args_4, (caddr_t) argp,
		(xdrproc_t) _DtCm_xdr_Table_Status_4, (caddr_t) &clnt_res,
		TIMEOUT) != RPC_SUCCESS) {
		return (NULL);
	}
	return (&clnt_res);
}

Table_Status_4 *
_DtCm_rtable_rename_4(Table_Op_Args_4 *argp, _DtCm_Connection *clnt)
{
	static Table_Status_4 clnt_res;

	memset((char *)&clnt_res, 0, sizeof(clnt_res));
	if (_DtCm_clnt_call (clnt, rtable_rename,
		(xdrproc_t) _DtCm_xdr_Table_Op_Args_4, (caddr_t) argp,
		(xdrproc_t) _DtCm_xdr_Table_Status_4, (caddr_t) &clnt_res,
		TIMEOUT) != RPC_SUCCESS) {
		return (NULL);
	}
	return (&clnt_res);
}
