#include <EUSCompat.h>

/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#include "rtable4.h"

bool_t
_DtCm_xdr_Buffer_4 (XDR *xdrs, Buffer_4 *objp)
{
	register int32_t *buf;

	 if (!xdr_string (xdrs, objp, ~0))
		 return FALSE;
	return TRUE;
}

bool_t
_DtCm_xdr_Interval_4 (XDR *xdrs, Interval_4 *objp)
{
	register int32_t *buf;

	 if (!xdr_enum (xdrs, (enum_t *) objp))
		 return FALSE;
	return TRUE;
}

bool_t
_DtCm_xdr_Period_4 (XDR *xdrs, Period_4 *objp)
{
	register int32_t *buf;

	 if (!_DtCm_xdr_Interval_4 (xdrs, &objp->period))
		 return FALSE;
	 if (!xdr_int (xdrs, &objp->nth))
		 return FALSE;
	 if (!xdr_time_t (xdrs, &objp->enddate))
		 return FALSE;
	return TRUE;
}

bool_t
_DtCm_xdr_Event_Type_4 (XDR *xdrs, Event_Type_4 *objp)
{
	register int32_t *buf;

	 if (!xdr_enum (xdrs, (enum_t *) objp))
		 return FALSE;
	return TRUE;
}

bool_t
_DtCm_xdr_Options_4 (XDR *xdrs, Options_4 *objp)
{
	register int32_t *buf;

	 if (!xdr_enum (xdrs, (enum_t *) objp))
		 return FALSE;
	return TRUE;
}

bool_t
_DtCm_xdr_Tag_4 (XDR *xdrs, Tag_4 *objp)
{
	register int32_t *buf;

	 if (!_DtCm_xdr_Event_Type_4 (xdrs, &objp->tag))
		 return FALSE;
	 if (!xdr_int (xdrs, &objp->showtime))
		 return FALSE;
	 if (!xdr_pointer (xdrs, (char **)&objp->next, sizeof (Tag_4), (xdrproc_t) _DtCm_xdr_Tag_4))
		 return FALSE;
	return TRUE;
}

bool_t
_DtCm_xdr_Privacy_Level_4 (XDR *xdrs, Privacy_Level_4 *objp)
{
	register int32_t *buf;

	 if (!xdr_enum (xdrs, (enum_t *) objp))
		 return FALSE;
	return TRUE;
}

bool_t
_DtCm_xdr_Attribute_4 (XDR *xdrs, Attribute_4 *objp)
{
	register int32_t *buf;

	 if (!xdr_pointer (xdrs, (char **)&objp->next, sizeof (Attribute_4), (xdrproc_t) _DtCm_xdr_Attribute_4))
		 return FALSE;
	 if (!_DtCm_xdr_Buffer_4 (xdrs, &objp->attr))
		 return FALSE;
	 if (!_DtCm_xdr_Buffer_4 (xdrs, &objp->value))
		 return FALSE;
	 if (!_DtCm_xdr_Buffer_4 (xdrs, &objp->clientdata))
		 return FALSE;
	return TRUE;
}

bool_t
_DtCm_xdr_Attr_4 (XDR *xdrs, Attr_4 *objp)
{
	register int32_t *buf;

	 if (!xdr_pointer (xdrs, (char **)objp, sizeof (Attribute_4), (xdrproc_t) _DtCm_xdr_Attribute_4))
		 return FALSE;
	return TRUE;
}

bool_t
_DtCm_xdr_Except_4 (XDR *xdrs, Except_4 *objp)
{
	register int32_t *buf;

	 if (!xdr_int (xdrs, &objp->ordinal))
		 return FALSE;
	 if (!xdr_pointer (xdrs, (char **)&objp->next, sizeof (Except_4), (xdrproc_t) _DtCm_xdr_Except_4))
		 return FALSE;
	return TRUE;
}

bool_t
_DtCm_xdr_Exception_4 (XDR *xdrs, Exception_4 *objp)
{
	register int32_t *buf;

	 if (!xdr_pointer (xdrs, (char **)objp, sizeof (Except_4), (xdrproc_t) _DtCm_xdr_Except_4))
		 return FALSE;
	return TRUE;
}

bool_t
_DtCm_xdr_Id_4 (XDR *xdrs, Id_4 *objp)
{
	register int32_t *buf;

	 if (!xdr_time_t (xdrs, &objp->tick))
		 return FALSE;
	 if (!xdr_long (xdrs, &objp->key))
		 return FALSE;
	return TRUE;
}

bool_t
_DtCm_xdr_Uid_4 (XDR *xdrs, Uid_4 *objp)
{
	register int32_t *buf;

	 if (!_DtCm_xdr_Id_4 (xdrs, &objp->appt_id))
		 return FALSE;
	 if (!xdr_pointer (xdrs, (char **)&objp->next, sizeof (Uid_4), (xdrproc_t) _DtCm_xdr_Uid_4))
		 return FALSE;
	return TRUE;
}

bool_t
_DtCm_xdr_Appt_Status_4 (XDR *xdrs, Appt_Status_4 *objp)
{
	register int32_t *buf;

	 if (!xdr_enum (xdrs, (enum_t *) objp))
		 return FALSE;
	return TRUE;
}

bool_t
_DtCm_xdr_Appt_4 (XDR *xdrs, Appt_4 *objp)
{
	register int32_t *buf;

	 if (!_DtCm_xdr_Id_4 (xdrs, &objp->appt_id))
		 return FALSE;
	 if (!xdr_pointer (xdrs, (char **)&objp->tag, sizeof (Tag_4), (xdrproc_t) _DtCm_xdr_Tag_4))
		 return FALSE;
	 if (!xdr_int (xdrs, &objp->duration))
		 return FALSE;
	 if (!xdr_int (xdrs, &objp->ntimes))
		 return FALSE;
	 if (!_DtCm_xdr_Buffer_4 (xdrs, &objp->what))
		 return FALSE;
	 if (!_DtCm_xdr_Period_4 (xdrs, &objp->period))
		 return FALSE;
	 if (!_DtCm_xdr_Buffer_4 (xdrs, &objp->author))
		 return FALSE;
	 if (!_DtCm_xdr_Buffer_4 (xdrs, &objp->client_data))
		 return FALSE;
	 if (!xdr_pointer (xdrs, (char **)&objp->exception, sizeof (Except_4), (xdrproc_t) _DtCm_xdr_Except_4))
		 return FALSE;
	 if (!xdr_pointer (xdrs, (char **)&objp->attr, sizeof (Attribute_4), (xdrproc_t) _DtCm_xdr_Attribute_4))
		 return FALSE;
	 if (!_DtCm_xdr_Appt_Status_4 (xdrs, &objp->appt_status))
		 return FALSE;
	 if (!_DtCm_xdr_Privacy_Level_4 (xdrs, &objp->privacy))
		 return FALSE;
	 if (!xdr_pointer (xdrs, (char **)&objp->next, sizeof (Appt_4), (xdrproc_t) _DtCm_xdr_Appt_4))
		 return FALSE;
	return TRUE;
}

bool_t
_DtCm_xdr_Abb_Appt_4 (XDR *xdrs, Abb_Appt_4 *objp)
{
	register int32_t *buf;

	 if (!_DtCm_xdr_Id_4 (xdrs, &objp->appt_id))
		 return FALSE;
	 if (!xdr_pointer (xdrs, (char **)&objp->tag, sizeof (Tag_4), (xdrproc_t) _DtCm_xdr_Tag_4))
		 return FALSE;
	 if (!_DtCm_xdr_Buffer_4 (xdrs, &objp->what))
		 return FALSE;
	 if (!xdr_int (xdrs, &objp->duration))
		 return FALSE;
	 if (!_DtCm_xdr_Period_4 (xdrs, &objp->period))
		 return FALSE;
	 if (!xdr_pointer (xdrs, (char **)&objp->next, sizeof (Abb_Appt_4), (xdrproc_t) _DtCm_xdr_Abb_Appt_4))
		 return FALSE;
	 if (!_DtCm_xdr_Appt_Status_4 (xdrs, &objp->appt_status))
		 return FALSE;
	 if (!_DtCm_xdr_Privacy_Level_4 (xdrs, &objp->privacy))
		 return FALSE;
	return TRUE;
}

bool_t
_DtCm_xdr_Apptid_4 (XDR *xdrs, Apptid_4 *objp)
{
	register int32_t *buf;

	 if (!xdr_pointer (xdrs, (char **)&objp->oid, sizeof (Id_4), (xdrproc_t) _DtCm_xdr_Id_4))
		 return FALSE;
	 if (!xdr_pointer (xdrs, (char **)&objp->new_appt, sizeof (Appt_4), (xdrproc_t) _DtCm_xdr_Appt_4))
		 return FALSE;
	 if (!_DtCm_xdr_Options_4 (xdrs, &objp->option))
		 return FALSE;
	return TRUE;
}

bool_t
_DtCm_xdr_Reminder_4 (XDR *xdrs, Reminder_4 *objp)
{
	register int32_t *buf;

	 if (!_DtCm_xdr_Id_4 (xdrs, &objp->appt_id))
		 return FALSE;
	 if (!xdr_time_t (xdrs, &objp->tick))
		 return FALSE;
	 if (!_DtCm_xdr_Attribute_4 (xdrs, &objp->attr))
		 return FALSE;
	 if (!xdr_pointer (xdrs, (char **)&objp->next, sizeof (Reminder_4), (xdrproc_t) _DtCm_xdr_Reminder_4))
		 return FALSE;
	return TRUE;
}

bool_t
_DtCm_xdr_Table_Res_Type_4 (XDR *xdrs, Table_Res_Type_4 *objp)
{
	register int32_t *buf;

	 if (!xdr_enum (xdrs, (enum_t *) objp))
		 return FALSE;
	return TRUE;
}

bool_t
_DtCm_xdr_Table_Res_List_4 (XDR *xdrs, Table_Res_List_4 *objp)
{
	register int32_t *buf;

	 if (!_DtCm_xdr_Table_Res_Type_4 (xdrs, &objp->tag))
		 return FALSE;
	switch (objp->tag) {
	case AP_4:
		 if (!xdr_pointer (xdrs, (char **)&objp->Table_Res_List_4_u.a, sizeof (Appt_4), (xdrproc_t) _DtCm_xdr_Appt_4))
			 return FALSE;
		break;
	case RM_4:
		 if (!xdr_pointer (xdrs, (char **)&objp->Table_Res_List_4_u.r, sizeof (Reminder_4), (xdrproc_t) _DtCm_xdr_Reminder_4))
			 return FALSE;
		break;
	case AB_4:
		 if (!xdr_pointer (xdrs, (char **)&objp->Table_Res_List_4_u.b, sizeof (Abb_Appt_4), (xdrproc_t) _DtCm_xdr_Abb_Appt_4))
			 return FALSE;
		break;
	case ID_4:
		 if (!xdr_pointer (xdrs, (char **)&objp->Table_Res_List_4_u.i, sizeof (Uid_4), (xdrproc_t) _DtCm_xdr_Uid_4))
			 return FALSE;
		break;
	default:
		break;
	}
	return TRUE;
}

bool_t
_DtCm_xdr_Access_Status_4 (XDR *xdrs, Access_Status_4 *objp)
{
	register int32_t *buf;

	 if (!xdr_enum (xdrs, (enum_t *) objp))
		 return FALSE;
	return TRUE;
}

bool_t
_DtCm_xdr_Table_Res_4 (XDR *xdrs, Table_Res_4 *objp)
{
	register int32_t *buf;

	 if (!_DtCm_xdr_Access_Status_4 (xdrs, &objp->status))
		 return FALSE;
	 if (!_DtCm_xdr_Table_Res_List_4 (xdrs, &objp->res))
		 return FALSE;
	return TRUE;
}
#define access_none_4 0x0 /* owner only */
#define access_read_4 0x1
#define access_write_4 0x2
#define access_delete_4 0x4
#define access_exec_4 0x8 /* execution permission is a hack! */
#define WORLD "world" /* special user */

bool_t
_DtCm_xdr_Access_Entry_4 (XDR *xdrs, Access_Entry_4 *objp)
{
	register int32_t *buf;

	 if (!_DtCm_xdr_Buffer_4 (xdrs, &objp->who))
		 return FALSE;
	 if (!xdr_int (xdrs, &objp->access_type))
		 return FALSE;
	 if (!xdr_pointer (xdrs, (char **)&objp->next, sizeof (Access_Entry_4), (xdrproc_t) _DtCm_xdr_Access_Entry_4))
		 return FALSE;
	return TRUE;
}

bool_t
_DtCm_xdr_Access_Args_4 (XDR *xdrs, Access_Args_4 *objp)
{
	register int32_t *buf;

	 if (!_DtCm_xdr_Buffer_4 (xdrs, &objp->target))
		 return FALSE;
	 if (!xdr_pointer (xdrs, (char **)&objp->access_list, sizeof (Access_Entry_4), (xdrproc_t) _DtCm_xdr_Access_Entry_4))
		 return FALSE;
	return TRUE;
}

bool_t
_DtCm_xdr_Range_4 (XDR *xdrs, Range_4 *objp)
{
	register int32_t *buf;

	 if (!xdr_time_t (xdrs, &objp->key1))
		 return FALSE;
	 if (!xdr_time_t (xdrs, &objp->key2))
		 return FALSE;
	 if (!xdr_pointer (xdrs, (char **)&objp->next, sizeof (Range_4), (xdrproc_t) _DtCm_xdr_Range_4))
		 return FALSE;
	return TRUE;
}

bool_t
_DtCm_xdr_Keyrange_4 (XDR *xdrs, Keyrange_4 *objp)
{
	register int32_t *buf;

	 if (!xdr_long (xdrs, &objp->key))
		 return FALSE;
	 if (!xdr_time_t (xdrs, &objp->tick1))
		 return FALSE;
	 if (!xdr_time_t (xdrs, &objp->tick2))
		 return FALSE;
	 if (!xdr_pointer (xdrs, (char **)&objp->next, sizeof (Keyrange_4), (xdrproc_t) _DtCm_xdr_Keyrange_4))
		 return FALSE;
	return TRUE;
}

bool_t
_DtCm_xdr_Uidopt_4 (XDR *xdrs, Uidopt_4 *objp)
{
	register int32_t *buf;

	 if (!_DtCm_xdr_Id_4 (xdrs, &objp->appt_id))
		 return FALSE;
	 if (!_DtCm_xdr_Options_4 (xdrs, &objp->option))
		 return FALSE;
	 if (!xdr_pointer (xdrs, (char **)&objp->next, sizeof (Uidopt_4), (xdrproc_t) _DtCm_xdr_Uidopt_4))
		 return FALSE;
	return TRUE;
}

bool_t
_DtCm_xdr_Table_Args_Type_4 (XDR *xdrs, Table_Args_Type_4 *objp)
{
	register int32_t *buf;

	 if (!xdr_enum (xdrs, (enum_t *) objp))
		 return FALSE;
	return TRUE;
}

bool_t
_DtCm_xdr_Args_4 (XDR *xdrs, Args_4 *objp)
{
	register int32_t *buf;

	 if (!_DtCm_xdr_Table_Args_Type_4 (xdrs, &objp->tag))
		 return FALSE;
	switch (objp->tag) {
	case TICK_4:
		 if (!xdr_time_t (xdrs, &objp->Args_4_u.tick))
			 return FALSE;
		break;
	case APPTID_4:
		 if (!_DtCm_xdr_Apptid_4 (xdrs, &objp->Args_4_u.apptid))
			 return FALSE;
		break;
	case UID_4:
		 if (!xdr_pointer (xdrs, (char **)&objp->Args_4_u.key, sizeof (Uid_4), (xdrproc_t) _DtCm_xdr_Uid_4))
			 return FALSE;
		break;
	case APPT_4:
		 if (!xdr_pointer (xdrs, (char **)&objp->Args_4_u.appt, sizeof (Appt_4), (xdrproc_t) _DtCm_xdr_Appt_4))
			 return FALSE;
		break;
	case RANGE_4:
		 if (!xdr_pointer (xdrs, (char **)&objp->Args_4_u.range, sizeof (Range_4), (xdrproc_t) _DtCm_xdr_Range_4))
			 return FALSE;
		break;
	case KEYRANGE_4:
		 if (!xdr_pointer (xdrs, (char **)&objp->Args_4_u.keyrange, sizeof (Keyrange_4), (xdrproc_t) _DtCm_xdr_Keyrange_4))
			 return FALSE;
		break;
	case UIDOPT_4:
		 if (!xdr_pointer (xdrs, (char **)&objp->Args_4_u.uidopt, sizeof (Uidopt_4), (xdrproc_t) _DtCm_xdr_Uidopt_4))
			 return FALSE;
		break;
	default:
		return FALSE;
	}
	return TRUE;
}

bool_t
_DtCm_xdr_Table_Args_4 (XDR *xdrs, Table_Args_4 *objp)
{
	register int32_t *buf;

	 if (!_DtCm_xdr_Buffer_4 (xdrs, &objp->target))
		 return FALSE;
	 if (!_DtCm_xdr_Args_4 (xdrs, &objp->args))
		 return FALSE;
	 if (!xdr_int (xdrs, &objp->pid))
		 return FALSE;
	return TRUE;
}

bool_t
_DtCm_xdr_Registration_4 (XDR *xdrs, Registration_4 *objp)
{
	register int32_t *buf;


	if (xdrs->x_op == XDR_ENCODE) {
		 if (!_DtCm_xdr_Buffer_4 (xdrs, &objp->target))
			 return FALSE;
		buf = XDR_INLINE (xdrs, 3 * BYTES_PER_XDR_UNIT);
		if (buf == NULL) {
			 if (!xdr_u_long (xdrs, &objp->prognum))
				 return FALSE;
			 if (!xdr_u_long (xdrs, &objp->versnum))
				 return FALSE;
			 if (!xdr_u_long (xdrs, &objp->procnum))
				 return FALSE;

		} else {
		IXDR_PUT_U_LONG(buf, objp->prognum);
		IXDR_PUT_U_LONG(buf, objp->versnum);
		IXDR_PUT_U_LONG(buf, objp->procnum);
		}
		 if (!xdr_pointer (xdrs, (char **)&objp->next, sizeof (Registration_4), (xdrproc_t) _DtCm_xdr_Registration_4))
			 return FALSE;
		 if (!xdr_int (xdrs, &objp->pid))
			 return FALSE;
		return TRUE;
	} else if (xdrs->x_op == XDR_DECODE) {
		 if (!_DtCm_xdr_Buffer_4 (xdrs, &objp->target))
			 return FALSE;
		buf = XDR_INLINE (xdrs, 3 * BYTES_PER_XDR_UNIT);
		if (buf == NULL) {
			 if (!xdr_u_long (xdrs, &objp->prognum))
				 return FALSE;
			 if (!xdr_u_long (xdrs, &objp->versnum))
				 return FALSE;
			 if (!xdr_u_long (xdrs, &objp->procnum))
				 return FALSE;

		} else {
		objp->prognum = IXDR_GET_U_LONG(buf);
		objp->versnum = IXDR_GET_U_LONG(buf);
		objp->procnum = IXDR_GET_U_LONG(buf);
		}
		 if (!xdr_pointer (xdrs, (char **)&objp->next, sizeof (Registration_4), (xdrproc_t) _DtCm_xdr_Registration_4))
			 return FALSE;
		 if (!xdr_int (xdrs, &objp->pid))
			 return FALSE;
	 return TRUE;
	}

	 if (!_DtCm_xdr_Buffer_4 (xdrs, &objp->target))
		 return FALSE;
	 if (!xdr_u_long (xdrs, &objp->prognum))
		 return FALSE;
	 if (!xdr_u_long (xdrs, &objp->versnum))
		 return FALSE;
	 if (!xdr_u_long (xdrs, &objp->procnum))
		 return FALSE;
	 if (!xdr_pointer (xdrs, (char **)&objp->next, sizeof (Registration_4), (xdrproc_t) _DtCm_xdr_Registration_4))
		 return FALSE;
	 if (!xdr_int (xdrs, &objp->pid))
		 return FALSE;
	return TRUE;
}

bool_t
_DtCm_xdr_Table_Op_Args_4 (XDR *xdrs, Table_Op_Args_4 *objp)
{
	register int32_t *buf;

	 if (!_DtCm_xdr_Buffer_4 (xdrs, &objp->target))
		 return FALSE;
	 if (!_DtCm_xdr_Buffer_4 (xdrs, &objp->new_target))
		 return FALSE;
	return TRUE;
}

bool_t
_DtCm_xdr_Table_Status_4 (XDR *xdrs, Table_Status_4 *objp)
{
	register int32_t *buf;

	 if (!xdr_enum (xdrs, (enum_t *) objp))
		 return FALSE;
	return TRUE;
}

bool_t
_DtCm_xdr_Registration_Status_4 (XDR *xdrs, Registration_Status_4 *objp)
{
	register int32_t *buf;

	 if (!xdr_enum (xdrs, (enum_t *) objp))
		 return FALSE;
	return TRUE;
}

/*
 * rtable_delete and rtable_change take over the functionality of
 * rtable_delete_instance and rtable_change_instance repectively.
 * rtable_delete_instance and rtable_change_instance are now dummy
 * routines exist for backward compatibility purpose and return
 * access_notsupported.
 */
